/**
 * Nombres en español, en lenguaje sencillo, para los 253 componentes que usa
 * RADKFILE. Se emplean para construir las historias mnemotécnicas.
 *
 * Varios componentes aparecen en RADKFILE con un kanji "representante" en vez
 * del radical suelto (por ejemplo 汁 representa 氵). Aquí se guarda el nombre
 * del radical real, no el del kanji representante.
 */
export const COMPONENT_NAMES = {
  一: 'una línea',
  '｜': 'un palo vertical',
  丶: 'una gota',
  ノ: 'un trazo inclinado',
  乙: 'un gancho',
  亅: 'un anzuelo',
  二: 'dos líneas',
  亠: 'una tapa',
  人: 'una persona',
  化: 'una persona de pie al lado',
  个: 'un techito',
  儿: 'dos piernas',
  入: 'entrar',
  ハ: 'algo que se separa',
  并: 'dos cuernitos',
  冂: 'una caja abierta',
  冖: 'un gorro',
  冫: 'hielo',
  几: 'una mesita',
  凵: 'un cuenco',
  刀: 'un cuchillo',
  刈: 'una espada al lado',
  力: 'fuerza',
  勹: 'unos brazos que envuelven',
  匕: 'una cuchara',
  匚: 'una caja abierta de lado',
  十: 'una cruz',
  卜: 'un palito de adivinar',
  卩: 'un sello',
  厂: 'un acantilado',
  厶: 'algo privado',
  又: 'una mano',
  マ: 'un ganchito',
  九: 'el número nueve',
  ユ: 'una manita',
  乃: 'una curva',
  乞: 'pedir algo',
  込: 'un camino',
  口: 'una boca',
  囗: 'una cerca',
  土: 'tierra',
  士: 'un guerrero',
  夂: 'unos pies que bajan',
  夕: 'el atardecer',
  大: 'algo grande',
  女: 'una mujer',
  子: 'un niño',
  宀: 'el techo de una casa',
  寸: 'una medida corta',
  小: 'algo pequeño',
  尚: 'todavía más',
  尢: 'una pierna doblada',
  尸: 'un cuerpo agachado',
  屮: 'un brote',
  山: 'una montaña',
  川: 'un río',
  巛: 'un río con corriente',
  工: 'una herramienta de trabajo',
  已: 'algo que ya terminó',
  巾: 'una tela',
  干: 'un escudo seco',
  幺: 'un hilito',
  广: 'un tejado inclinado',
  廴: 'un paso largo',
  廾: 'dos manos que sostienen',
  弋: 'una flecha con cuerda',
  弓: 'un arco',
  ヨ: 'una mano abierta',
  彑: 'un hocico',
  彡: 'unos pelitos brillantes',
  彳: 'unos pasos en el camino',
  忙: 'un corazón al lado',
  扎: 'una mano al lado',
  汁: 'agua',
  犯: 'un animal salvaje',
  艾: 'unas plantitas',
  邦: 'una aldea a la derecha',
  阡: 'una colina a la izquierda',
  也: 'también',
  亡: 'algo perdido',
  及: 'alcanzar',
  久: 'mucho tiempo',
  老: 'una persona mayor',
  心: 'un corazón',
  戈: 'una lanza',
  戸: 'una puerta',
  手: 'una mano',
  支: 'una rama que sostiene',
  攵: 'un golpecito',
  文: 'letras escritas',
  斗: 'un cucharón',
  斤: 'un hacha',
  方: 'una dirección',
  无: 'no tener nada',
  日: 'el sol',
  曰: 'una boca que habla',
  月: 'la luna',
  木: 'un árbol',
  欠: 'un bostezo',
  止: 'un pie que se detiene',
  歹: 'un hueso',
  殳: 'un palo de golpear',
  比: 'dos cosas que se comparan',
  毛: 'un pelo',
  氏: 'una familia',
  气: 'vapor',
  水: 'agua',
  火: 'fuego',
  杰: 'llamitas de fuego',
  爪: 'una garra',
  父: 'un papá',
  爻: 'dos líneas cruzadas',
  爿: 'una cama de pie',
  片: 'un trocito',
  牛: 'una vaca',
  犬: 'un perro',
  礼: 'un altar al lado',
  王: 'un rey',
  元: 'el origen',
  井: 'un pozo',
  勿: 'algo prohibido',
  尤: 'aún más',
  五: 'el número cinco',
  屯: 'un campamento',
  巴: 'un remolino',
  毋: 'no hacerlo',
  玄: 'algo misterioso',
  瓦: 'una teja',
  甘: 'algo dulce',
  生: 'vida',
  用: 'usar algo',
  田: 'un campo de arroz',
  疋: 'un pie',
  疔: 'una enfermedad',
  癶: 'dos pies que suben',
  白: 'algo blanco',
  皮: 'una piel',
  皿: 'un plato',
  目: 'un ojo',
  矛: 'una lanza larga',
  矢: 'una flecha',
  石: 'una piedra',
  示: 'un altar',
  禹: 'un insecto antiguo',
  禾: 'una espiga de arroz',
  穴: 'una cueva',
  立: 'alguien de pie',
  初: 'una ropa al lado',
  世: 'el mundo',
  巨: 'algo gigante',
  冊: 'un libro',
  母: 'una mamá',
  買: 'una red',
  牙: 'un colmillo',
  瓜: 'un melón',
  竹: 'bambú',
  米: 'arroz',
  糸: 'un hilo',
  缶: 'una lata',
  羊: 'una oveja',
  羽: 'unas plumas',
  而: 'una barba',
  耒: 'un arado',
  耳: 'una oreja',
  聿: 'un pincel',
  肉: 'carne',
  自: 'uno mismo',
  至: 'llegar',
  臼: 'un mortero',
  舌: 'una lengua',
  舟: 'un barco',
  艮: 'quedarse quieto',
  色: 'un color',
  虍: 'un tigre',
  虫: 'un insecto',
  血: 'sangre',
  行: 'una calle',
  衣: 'ropa',
  西: 'el oeste',
  臣: 'un sirviente',
  見: 'ver',
  角: 'un cuerno',
  言: 'palabras',
  谷: 'un valle',
  豆: 'un frijol',
  豕: 'un cerdo',
  豸: 'una bestia',
  貝: 'una concha de dinero',
  赤: 'el color rojo',
  走: 'correr',
  足: 'un pie',
  身: 'un cuerpo',
  車: 'un carro',
  辛: 'algo picante',
  辰: 'un dragón',
  酉: 'una jarra de sake',
  釆: 'separar granitos',
  里: 'una aldea',
  舛: 'dos pies opuestos',
  麦: 'trigo',
  金: 'metal',
  長: 'algo largo',
  門: 'un portón',
  隶: 'atrapar',
  隹: 'un pajarito',
  雨: 'lluvia',
  青: 'el color azul',
  非: 'algo que no es',
  奄: 'cubrir de repente',
  岡: 'una colina',
  免: 'librarse de algo',
  斉: 'todo ordenado',
  面: 'una cara',
  革: 'cuero',
  韭: 'un puerro',
  音: 'un sonido',
  頁: 'una cabeza',
  風: 'viento',
  飛: 'volar',
  食: 'comida',
  首: 'un cuello',
  香: 'un aroma',
  品: 'varios productos',
  馬: 'un caballo',
  骨: 'un hueso',
  高: 'algo alto',
  髟: 'pelo largo',
  鬥: 'una pelea',
  鬯: 'un licor',
  鬲: 'un caldero',
  鬼: 'un fantasma',
  竜: 'un dragón',
  韋: 'cuero curtido',
  魚: 'un pez',
  鳥: 'un pájaro',
  鹵: 'sal',
  鹿: 'un ciervo',
  麻: 'cáñamo',
  亀: 'una tortuga',
  滴: 'una gota que cae',
  黄: 'el color amarillo',
  黒: 'el color negro',
  黍: 'mijo',
  黹: 'un bordado',
  無: 'la nada',
  歯: 'un diente',
  黽: 'una rana',
  鼎: 'una olla de tres patas',
  鼓: 'un tambor',
  鼠: 'un ratón',
  鼻: 'una nariz',
  齊: 'todo parejo',
  龠: 'una flauta',
}

/** Componentes demasiado genéricos para protagonizar una historia. */
export const WEAK_COMPONENTS = new Set([
  '一',
  '｜',
  '丶',
  'ノ',
  '亅',
  'マ',
  'ユ',
  'ヨ',
  '乙',
  '彑',
  '爻',
  '也',
  '已',
])
