/**
 * Fotos extra de carteles reales (Wikimedia Commons), sobre todo estaciones
 * y señales de la calle con kanji frecuentes.
 */

export const STREET_PHOTOS_EXTRA = [
  {
    id: "estacion-tokyo-este",
    file: "/photos/estacion-tokyo.jpg",
    commonsTitle: "File:東京駅 駅名標.jpg",
    focus: "東",
    text: "東京",
    textReading: "とうきょう",
    where: "Estación de Tokio, andén del Tōkaidō",
    caption: "El cartel dice 東京. 東 suena とう, su lectura on: en los nombres de ciudad casi siempre se usa on.",
    credit: {
      author: "豊橋人",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%9D%B1%E4%BA%AC%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-tokyo-capital",
    file: "/photos/estacion-tokyo.jpg",
    commonsTitle: "File:東京駅 駅名標.jpg",
    focus: "京",
    text: "東京",
    textReading: "とうきょう",
    where: "Estación de Tokio, andén del Tōkaidō",
    caption: "京 suena きょう, también lectura on. 東京 es un compuesto clásico: on + on.",
    credit: {
      author: "豊橋人",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%9D%B1%E4%BA%AC%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-shin-osaka-nuevo",
    file: "/photos/estacion-shin-osaka.jpg",
    commonsTitle: "File:新大阪駅 駅名標.jpg",
    focus: "新",
    text: "新大阪",
    textReading: "しんおおさか",
    where: "Estación de Shin-Osaka, Shinkansen",
    caption: "新大阪 es «Osaka nueva». 新 suena しん, su lectura on, como en casi todos los compuestos.",
    credit: {
      author: "JNR 201",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%96%B0%E5%A4%A7%E9%98%AA%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-shin-osaka-grande",
    file: "/photos/estacion-shin-osaka.jpg",
    commonsTitle: "File:新大阪駅 駅名標.jpg",
    focus: "大",
    text: "新大阪",
    textReading: "しんおおさか",
    where: "Estación de Shin-Osaka, Shinkansen",
    caption: "大 suena おお, kun, porque 大阪 se lee así: no es だいさか. Los nombres de lugar a veces rompen la regla.",
    credit: {
      author: "JNR 201",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%96%B0%E5%A4%A7%E9%98%AA%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-osaka",
    file: "/photos/estacion-osaka.jpg",
    commonsTitle: "File:大阪駅名標 (東海道本線上りホーム).jpg",
    focus: "阪",
    text: "大阪",
    textReading: "おおさか",
    where: "Estación de Osaka, línea Tōkaidō",
    caption: "大阪 se lee おおさか. 阪 no usa su on はん aquí: es una lectura fija del nombre de la ciudad.",
    credit: {
      author: "Wikimedia Commons",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%A4%A7%E9%98%AA%E9%A7%85%E5%90%8D%E6%A8%99_%28%E6%9D%B1%E6%B5%B7%E9%81%93%E6%9C%AC%E7%B7%9A%E4%B8%8A%E3%82%8A%E3%83%9B%E3%83%BC%E3%83%A0%29.jpg"
    },
  },
  {
    id: "estacion-kobe",
    file: "/photos/estacion-kobe-sannomiya.jpg",
    commonsTitle: "File:神戸三宮駅 駅名標.jpg",
    focus: "神",
    text: "神戸三宮",
    textReading: "こうべさんのみや",
    where: "Estación Hankyu de Kobe-Sannomiya",
    caption: "神戸 se lee こうべ. 神 suena こう (on), no かみ: es el nombre de la ciudad, no «dios».",
    credit: {
      author: "JNR 201",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E7%A5%9E%E6%88%B8%E4%B8%89%E5%AE%AE%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-kochi",
    file: "/photos/estacion-kochi.jpg",
    commonsTitle: "File:高知駅駅名標.JPG",
    focus: "高",
    text: "高知",
    textReading: "こうち",
    where: "Estación de Kōchi",
    caption: "高知 se lee こうち. 高 suena こう, lectura on, como en muchos nombres de prefectura.",
    credit: {
      author: "Own work",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%AB%98%E7%9F%A5%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.JPG"
    },
  },
  {
    id: "estacion-hamadera",
    file: "/photos/estacion-hamadera.jpg",
    commonsTitle: "File:浜寺公園駅 駅名標.jpg",
    focus: "公",
    text: "浜寺公園",
    textReading: "はまでらこうえん",
    where: "Estación de Hamadera-kōen",
    caption: "公園 (parque) se lee こうえん: 公 suena こう, on. En Japón, 公園 en un nombre de estación es casi siempre un parque de verdad.",
    credit: {
      author: "Tatsuya tetsudo",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%B5%9C%E5%AF%BA%E5%85%AC%E5%9C%92%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-nishi-otsuka",
    file: "/photos/estacion-nishi-otsuka.jpg",
    commonsTitle: "File:西大塚駅名標.jpg",
    focus: "西",
    text: "西大塚",
    textReading: "にしおおつか",
    where: "Estación de Nishi-Ōtsuka",
    caption: "西 suena にし, su lectura kun. En nombres de estación, 東/西/南/北 casi siempre van en kun: «el lado oeste».",
    credit: {
      author: "Quu72",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E8%A5%BF%E5%A4%A7%E5%A1%9A%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-saijo",
    file: "/photos/estacion-saijo.jpg",
    commonsTitle: "File:西条駅駅名標.jpg",
    focus: "西",
    text: "西条",
    textReading: "さいじょう",
    where: "Estación de Saijō",
    caption: "西条 se lee さいじょう. Aquí 西 usa el on さい, no にし: es un nombre propio, no «oeste».",
    credit: {
      author: "AE-SkyLiner Sony NEX-5",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E8%A5%BF%E6%9D%A1%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-mojiko",
    file: "/photos/estacion-mojiko.jpg",
    commonsTitle: "File:門司港駅駅名標.jpg",
    focus: "港",
    text: "門司港",
    textReading: "もじこう",
    where: "Estación de Mojikō",
    caption: "港 suena こう, lectura on. En nombres de puerto y de estación, 港 casi nunca se lee みなと.",
    credit: {
      author: "玄海093",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%96%80%E5%8F%B8%E6%B8%AF%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-kyobashi",
    file: "/photos/estacion-kyobashi.jpg",
    commonsTitle: "File:京阪本線 京橋駅駅名標.jpg",
    focus: "橋",
    text: "京橋",
    textReading: "きょうばし",
    where: "Estación Keihan de Kyōbashi",
    caption: "京橋 se lee きょうばし. 橋 pasa de はし a ばし (rendaku) al ir detrás de otro kanji.",
    credit: {
      author: "Youmeeek",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%BA%AC%E9%98%AA%E6%9C%AC%E7%B7%9A_%E4%BA%AC%E6%A9%8B%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-nishi-muko",
    file: "/photos/estacion-nishi-muko.jpg",
    commonsTitle: "File:阪急京都本線西向日駅駅名標.jpg",
    focus: "日",
    text: "西向日",
    textReading: "にしむかい",
    where: "Estación Hankyu de Nishi-Mukō",
    caption: "西向日 lleva 日, el kanji más frecuente del idioma. Aquí no suena ひ ni にち: forma parte del nombre むかい.",
    credit: {
      author: "Youmeeek",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%98%AA%E6%80%A5%E4%BA%AC%E9%83%BD%E6%9C%AC%E7%B7%9A%E8%A5%BF%E5%90%91%E6%97%A5%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-omihachiman",
    file: "/photos/estacion-omihachiman.jpg",
    commonsTitle: "File:JR近江八幡駅駅名標.jpg",
    focus: "八",
    text: "近江八幡",
    textReading: "おうみはちまん",
    where: "Estación de Ōmi-Hachiman",
    caption: "八 suena はち, lectura on. En este nombre no se usa el kun や: es un compuesto on.",
    credit: {
      author: "計記録",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AJR%E8%BF%91%E6%B1%9F%E5%85%AB%E5%B9%A1%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-ominagaoka",
    file: "/photos/estacion-ominagaoka.jpg",
    commonsTitle: "File:JR近江長岡駅駅名標.jpg",
    focus: "長",
    text: "近江長岡",
    textReading: "おうみながおか",
    where: "Estación de Ōmi-Nagaoka",
    caption: "長岡 se lee ながおか. 長 suena なが, kun, como en muchos apellidos y topónimos.",
    credit: {
      author: "計記録",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AJR%E8%BF%91%E6%B1%9F%E9%95%B7%E5%B2%A1%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-nakakoen",
    file: "/photos/estacion-nakakoen.jpg",
    commonsTitle: "File:中公園駅1番線駅名標.jpg",
    focus: "中",
    text: "中公園",
    textReading: "なかこうえん",
    where: "Estación de Naka-kōen",
    caption: "中公園 mezcla kun y on: 中 es なか (kun, «en medio») y 公園 es こうえん (on).",
    credit: {
      author: "小田急4000系ファン",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%B8%AD%E5%85%AC%E5%9C%92%E9%A7%851%E7%95%AA%E7%B7%9A%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-tanimachi",
    file: "/photos/estacion-tanimachi-9.jpg",
    commonsTitle: "File:谷町九丁目駅 千日前線 駅名標.jpg",
    focus: "九",
    text: "谷町九丁目",
    textReading: "たにまちきゅうちょうめ",
    where: "Estación de Tanimachi 9-chōme, metro de Osaka",
    caption: "九丁目 se lee きゅうちょうめ. 九 suena きゅう (on): los números de barrio van casi siempre en on.",
    credit: {
      author: "Tatsuya tetsudo",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E8%B0%B7%E7%94%BA%E4%B9%9D%E4%B8%81%E7%9B%AE%E9%A7%85_%E5%8D%83%E6%97%A5%E5%89%8D%E7%B7%9A_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-nanko-higashi",
    file: "/photos/estacion-nanko-higashi.jpg",
    commonsTitle: "File:南港東駅駅名標.jpg",
    focus: "南",
    text: "南港東",
    textReading: "なんこうひがし",
    where: "Estación de Nankō-Higashi, metro de Osaka",
    caption: "南港東: 南 suena なん (on) y 東 al final suena ひがし (kun). El mismo kanji cambia según el sitio del nombre.",
    credit: {
      author: "小田急4000系ファン",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%8D%97%E6%B8%AF%E6%9D%B1%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-senri-chuo",
    file: "/photos/estacion-senri-chuo.jpg",
    commonsTitle: "File:北大阪急行千里中央駅駅名標.jpg",
    focus: "中",
    text: "千里中央",
    textReading: "せんりちゅうおう",
    where: "Estación de Senri-Chūō",
    caption: "中央 se lee ちゅうおう: 中 suena ちゅう (on). Es la palabra de siempre para «centro» de una ciudad o línea.",
    credit: {
      author: "小田急4000系ファン",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%8C%97%E5%A4%A7%E9%98%AA%E6%80%A5%E8%A1%8C%E5%8D%83%E9%87%8C%E4%B8%AD%E5%A4%AE%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-senri-chuo-sen",
    file: "/photos/estacion-senri-chuo.jpg",
    commonsTitle: "File:北大阪急行千里中央駅駅名標.jpg",
    focus: "千",
    text: "千里中央",
    textReading: "せんりちゅうおう",
    where: "Estación de Senri-Chūō",
    caption: "千 suena せん (on), la misma lectura de 一千. En el nombre 千里 el número va en on, como casi siempre en estaciones.",
    credit: {
      author: "小田急4000系ファン",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%8C%97%E5%A4%A7%E9%98%AA%E6%80%A5%E8%A1%8C%E5%8D%83%E9%87%8C%E4%B8%AD%E5%A4%AE%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-shin-hamamatsu",
    file: "/photos/estacion-shin-hamamatsu.jpg",
    commonsTitle: "File:新浜松(ET01)駅名標.jpg",
    focus: "浜",
    text: "新浜松",
    textReading: "しんはままつ",
    where: "Estación de Shin-Hamamatsu",
    caption: "浜松 se lee はままつ. 浜 usa el kun はま, típico de los nombres de costa.",
    credit: {
      author: "S-TRAIN for MM06",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%96%B0%E6%B5%9C%E6%9D%BE%28ET01%29%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-nagoyajo",
    file: "/photos/estacion-nagoyajo.jpg",
    commonsTitle: "File:Train station sign of Nagoyajo (Nagoya Castle) Station.jpg",
    focus: "名",
    text: "名古屋城",
    textReading: "なごやじょう",
    where: "Estación de Nagoyajō, metro de Nagoya",
    caption: "名古屋城: 名 suena な, una lectura corta que solo sale en este nombre de ciudad.",
    credit: {
      author: "KKPCW（Kyu3）",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3ATrain_station_sign_of_Nagoyajo_%28Nagoya_Castle%29_Station.jpg"
    },
  },
  {
    id: "estacion-oita",
    file: "/photos/estacion-oita.jpg",
    commonsTitle: "File:Oita Station Sign 2.jpg",
    focus: "分",
    text: "大分",
    textReading: "おおいた",
    where: "Estación de Ōita",
    caption: "大分 se lee おおいた. 分 no suena ふん ni ぶん: es el nombre de la prefectura, con lectura propia.",
    credit: {
      author: "そらみみ",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AOita_Station_Sign_2.jpg"
    },
  },
  {
    id: "estacion-shichijo",
    file: "/photos/estacion-shichijo.jpg",
    commonsTitle: "File:Shichijo Station Sign.jpg",
    focus: "七",
    text: "七条",
    textReading: "しちじょう",
    where: "Estación de Shichijō, Kioto",
    caption: "七条 se lee しちじょう. 七 suena しち (on). Las calles numeradas de Kioto usan on.",
    credit: {
      author: "そらみみ (Soramimi)",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AShichijo_Station_Sign.jpg"
    },
  },
  {
    id: "estacion-nanao",
    file: "/photos/estacion-nanao.jpg",
    commonsTitle: "File:Nanao Station Station Sign 202104.jpg",
    focus: "七",
    text: "七尾",
    textReading: "ななお",
    where: "Estación de Nanao",
    caption: "七尾 se lee ななお. Aquí 七 usa el kun なな, no しち: es un topónimo, no un número de calle.",
    credit: {
      author: "DiKnK8713",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3ANanao_Station_Station_Sign_202104.jpg"
    },
  },
  {
    id: "estacion-tetsudo-haku",
    file: "/photos/estacion-museo-ferroviario.jpg",
    commonsTitle: "File:鉄道博物館駅駅名標.jpg",
    focus: "鉄",
    text: "鉄道博物館",
    textReading: "てつどうはくぶつかん",
    where: "Estación del Museo del Ferrocarril",
    caption: "鉄道 se lee てつどう. 鉄 suena てつ, on: «camino de hierro», el compuesto clásico para tren.",
    credit: {
      author: "AE-SkyLiner This photo was taken with Sony NEX-5",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%89%84%E9%81%93%E5%8D%9A%E7%89%A9%E9%A4%A8%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-heiwa-dori",
    file: "/photos/estacion-heiwa-dori.jpg",
    commonsTitle: "File:平和通駅駅名標.jpg",
    focus: "通",
    text: "平和通",
    textReading: "へいわどおり",
    where: "Estación de Heiwa-dōri, Kitakyushu",
    caption: "通 al final de un nombre de calle se lee どおり (kun sonorizado), no つう. Es «avenida», no «atravesar».",
    credit: {
      author: "玄海093",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%B9%B3%E5%92%8C%E9%80%9A%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-asahikawa-yojo",
    file: "/photos/estacion-asahikawa-yojo.jpg",
    commonsTitle: "File:旭川四条駅 駅名標.jpg",
    focus: "四",
    text: "旭川四条",
    textReading: "あさひかわよじょう",
    where: "Estación de Asahikawa-Yojō",
    caption: "四条 se lee よじょう. 四 usa よ, una lectura kun típica de las calles numeradas.",
    credit: {
      author: "Mister0124",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%97%AD%E5%B7%9D%E5%9B%9B%E6%9D%A1%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-sangyo-doro",
    file: "/photos/estacion-sangyo-doro.jpg",
    commonsTitle: "File:産業道路駅 駅名標.jpg",
    focus: "業",
    text: "産業道路",
    textReading: "さんぎょうどうろ",
    where: "Estación de Sangyō-dōro",
    caption: "産業 se lee さんぎょう. 業 suena ぎょう, on: es la palabra normal para «industria».",
    credit: {
      author: "東経待機 This photo was taken with Canon PowerShot SX720 HS",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E7%94%A3%E6%A5%AD%E9%81%93%E8%B7%AF%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-wakayama-ko",
    file: "/photos/estacion-wakayama-ko.jpg",
    commonsTitle: "File:和歌山港駅駅名標.jpg",
    focus: "山",
    text: "和歌山港",
    textReading: "わかやまこう",
    where: "Estación de Wakayamako",
    caption: "和歌山 lleva 山. Aquí suena やま (kun), como en casi todos los nombres de prefectura con 山.",
    credit: {
      author: "しいな",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%92%8C%E6%AD%8C%E5%B1%B1%E6%B8%AF%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-kajiki",
    file: "/photos/estacion-kajiki.jpg",
    commonsTitle: "File:加治木駅駅名標.jpg",
    focus: "木",
    text: "加治木",
    textReading: "かじき",
    where: "Estación de Kajiki",
    caption: "加治木 se lee かじき. 木 no suena き ni もく a solas: el nombre se reparte entre los tres kanji.",
    credit: {
      author: "斉藤宗太郎",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%8A%A0%E6%B2%BB%E6%9C%A8%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-nissei-chuo",
    file: "/photos/estacion-nissei-chuo.jpg",
    commonsTitle: "File:日生中央駅駅名標.jpg",
    focus: "生",
    text: "日生中央",
    textReading: "にっせいちゅうおう",
    where: "Estación de Nissei-Chūō",
    caption: "日生 se lee にっせい. 生 suena せい (on) y 日 se acorta a にっ: sokuon delante de s.",
    credit: {
      author: "小田急4000系ファン",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%97%A5%E7%94%9F%E4%B8%AD%E5%A4%AE%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-otsumachi",
    file: "/photos/estacion-otsumachi.jpg",
    commonsTitle: "File:一畑電車大津町駅 駅名標.jpg",
    focus: "町",
    text: "大津町",
    textReading: "おおつまち",
    where: "Estación de Ōtsumachi",
    caption: "町 al final de un pueblo se lee まち (kun), no ちょう. 大津町 es «el pueblo de Ōtsu».",
    credit: {
      author: "ガラスパゴス",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%B8%80%E7%95%91%E9%9B%BB%E8%BB%8A%E5%A4%A7%E6%B4%A5%E7%94%BA%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-kami-ooka",
    file: "/photos/estacion-kamioka.jpg",
    commonsTitle: "File:Kamioooka Station Sign DSCN2609 20111026.JPG",
    focus: "上",
    text: "上大岡",
    textReading: "かみおおおか",
    where: "Estación de Kamiōoka, Keikyū",
    caption: "上大岡 se lee かみおおおか. 上 suena かみ (kun): «la Ōoka de arriba», no じょう.",
    credit: {
      author: "Ogiyoshisan",
      license: "Public domain",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AKamioooka_Station_Sign_DSCN2609_20111026.JPG"
    },
  },
  {
    id: "estacion-wajiki",
    file: "/photos/estacion-wajiki.jpg",
    commonsTitle: "File:和食駅駅名板 土佐くろしお鉄道 Aug 30, 2015.jpg",
    focus: "食",
    text: "和食",
    textReading: "わじき",
    where: "Estación de Wajiki, Kōchi",
    caption: "和食 aquí no es «comida japonesa» (わしょく). El pueblo se llama わじき: misma escritura, otra lectura.",
    credit: {
      author: "Kuruman",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%92%8C%E9%A3%9F%E9%A7%85%E9%A7%85%E5%90%8D%E6%9D%BF_%E5%9C%9F%E4%BD%90%E3%81%8F%E3%82%8D%E3%81%97%E3%81%8A%E9%89%84%E9%81%93_Aug_30%2C_2015.jpg"
    },
  },
  {
    id: "estacion-sakuragicho",
    file: "/photos/estacion-sakuragicho.jpg",
    commonsTitle: "File:Nostalgic train station sign board in Sakuragicho Station 02.jpg",
    focus: "町",
    text: "桜木町",
    textReading: "さくらぎちょう",
    where: "Estación de Sakuragichō, Yokohama",
    caption: "桜木町 se lee さくらぎちょう. 町 suena ちょう (on) porque es un barrio de ciudad, no un pueblo.",
    credit: {
      author: "電車(新幹線)でゴー！",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3ANostalgic_train_station_sign_board_in_Sakuragicho_Station_02.jpg"
    },
  },
  {
    id: "estacion-umekoji",
    file: "/photos/estacion-umekoji-kyoto-nishi.jpg",
    commonsTitle: "File:梅小路京都西(山陰本線)駅名標.jpg",
    focus: "京",
    text: "梅小路京都西",
    textReading: "うめこうじきょうとにし",
    where: "Estación de Umekōji-Kyōto-nishi",
    caption: "京都 se lee きょうと. 京 otra vez en on: es el nombre de la antigua capital.",
    credit: {
      author: "AE-SkyLiner This photo was taken with Sony NEX-5",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%A2%85%E5%B0%8F%E8%B7%AF%E4%BA%AC%E9%83%BD%E8%A5%BF%28%E5%B1%B1%E9%99%B0%E6%9C%AC%E7%B7%9A%29%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-osaka-namba",
    file: "/photos/estacion-osaka-namba.jpg",
    commonsTitle: "File:大阪難波駅 駅名標.jpg",
    focus: "波",
    text: "大阪難波",
    textReading: "おおさかなんば",
    where: "Estación Kintetsu de Ōsaka-Namba",
    caption: "難波 se lee なんば. 波 suena ば (on sonorizado): el nombre antiguo del barrio de Namba.",
    credit: {
      author: "JNR 201",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%A4%A7%E9%98%AA%E9%9B%A3%E6%B3%A2%E9%A7%85_%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "estacion-heiwa-dori-paz",
    file: "/photos/estacion-heiwa-dori.jpg",
    commonsTitle: "File:平和通駅駅名標.jpg",
    focus: "平",
    text: "平和通",
    textReading: "へいわどおり",
    where: "Estación de Heiwa-dōri",
    caption: "平和 se lee へいわ. 平 suena へい, on: «paz», el compuesto de siempre.",
    credit: {
      author: "玄海093",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%B9%B3%E5%92%8C%E9%80%9A%E9%A7%85%E9%A7%85%E5%90%8D%E6%A8%99.jpg"
    },
  },
  {
    id: "hiko-exit-clasico",
    file: "/photos/hiko-exit-clasico.jpg",
    commonsTitle: "File:Japanese old style Exit sign.jpg",
    focus: "非",
    text: "非常口",
    textReading: "ひじょうぐち",
    where: "Señal de emergencia en Japón",
    caption: "非常口 se lee ひじょうぐち. 非 suena ひ (on) y 口 pasa de くち a ぐち. Es la palabra legal para «salida de emergencia».",
    credit: {
      author: "椰子之樹",
      license: "Public domain",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AJapanese_old_style_Exit_sign.jpg"
    },
  },
  {
    id: "hiko-exit-suelo",
    file: "/photos/hiko-exit-suelo.jpg",
    commonsTitle: "File:床に書かれた非常口案内板.jpg",
    focus: "口",
    text: "非常口",
    textReading: "ひじょうぐち",
    where: "Pasillo con la salida de emergencia pintada en el suelo",
    caption: "El mismo 非常口, esta vez en el suelo. 口 suena ぐち: kun sonorizado al final de un compuesto.",
    credit: {
      author: "Wowwartonightkomuro",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%BA%8A%E3%81%AB%E6%9B%B8%E3%81%8B%E3%82%8C%E3%81%9F%E9%9D%9E%E5%B8%B8%E5%8F%A3%E6%A1%88%E5%86%85%E6%9D%BF.jpg"
    },
  },
  {
    id: "parking-sign",
    file: "/photos/parking-sign.jpg",
    commonsTitle: "File:駐車場看板.jpg",
    focus: "場",
    text: "駐車場",
    textReading: "ちゅうしゃじょう",
    where: "Aparcamiento en Japón",
    caption: "駐車場 se lee ちゅうしゃじょう. 場 suena じょう (on): «lugar de aparcar coches», todo el compuesto en on.",
    credit: {
      author: "Fd89igf",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%A7%90%E8%BB%8A%E5%A0%B4%E7%9C%8B%E6%9D%BF.jpg"
    },
  },
  {
    id: "parking-disabled",
    file: "/photos/parking-disabled.jpg",
    commonsTitle: "File:身障者用駐車場看板の例.jpg",
    focus: "車",
    text: "駐車場",
    textReading: "ちゅうしゃじょう",
    where: "Plaza de aparcamiento accesible",
    caption: "車 suena しゃ (on) dentro de 駐車, no くるま. En los carteles de tráfico el on es la norma.",
    credit: {
      author: "Wikimedia Commons",
      license: "Public domain",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E8%BA%AB%E9%9A%9C%E8%80%85%E7%94%A8%E9%A7%90%E8%BB%8A%E5%A0%B4%E7%9C%8B%E6%9D%BF%E3%81%AE%E4%BE%8B.jpg"
    },
  },
  {
    id: "parking-full",
    file: "/photos/parking-full.jpg",
    commonsTitle: "File:駐車場入口満車.jpg",
    focus: "満",
    text: "満車",
    textReading: "まんしゃ",
    where: "Entrada de un aparcamiento en Takamatsu",
    caption: "満車 se lee まんしゃ: «lleno». 満 suena まん (on). Si ves esto, no entres.",
    credit: {
      author: "運動会プロテインパワー",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%A7%90%E8%BB%8A%E5%A0%B4%E5%85%A5%E5%8F%A3%E6%BA%80%E8%BB%8A.jpg"
    },
  },
  {
    id: "taxi-empty",
    file: "/photos/taxi-empty.jpg",
    commonsTitle: "File:空車or満車 Vacancies or No Vacancies. (21866611849).jpg",
    focus: "空",
    text: "空車",
    textReading: "くうしゃ",
    where: "Aparcamiento en Osaka",
    caption: "空車 se lee くうしゃ: «hay sitio» (o un taxi libre). 空 suena くう (on), no そら.",
    credit: {
      author: "nobu3withfoxy from Iga,Mie, Japan",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E7%A9%BA%E8%BB%8Aor%E6%BA%80%E8%BB%8A_Vacancies_or_No_Vacancies._%2821866611849%29.jpg"
    },
  },
  {
    id: "one-way-exit",
    file: "/photos/one-way.jpg",
    commonsTitle: "File:丹沢湖・一方通行（出口） - panoramio.jpg",
    focus: "通",
    text: "一方通行",
    textReading: "いっぽうつうこう",
    where: "Lago Tanzawa, Kanagawa",
    caption: "一方通行 se lee いっぽうつうこう: «sentido único». 通 suena つう (on). 一 se acorta a いっ delante de ぽう.",
    credit: {
      author: "SYM50cc EMR",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%B8%B9%E6%B2%A2%E6%B9%96%E3%83%BB%E4%B8%80%E6%96%B9%E9%80%9A%E8%A1%8C%EF%BC%88%E5%87%BA%E5%8F%A3%EF%BC%89_-_panoramio.jpg"
    },
  },
  {
    id: "one-way-dir",
    file: "/photos/one-way.jpg",
    commonsTitle: "File:丹沢湖・一方通行（出口） - panoramio.jpg",
    focus: "方",
    text: "一方通行",
    textReading: "いっぽうつうこう",
    where: "Lago Tanzawa, Kanagawa",
    caption: "方 suena ぽう (on con handaku). 一方 es «una dirección»: compuesto on de manual.",
    credit: {
      author: "SYM50cc EMR",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%B8%B9%E6%B2%A2%E6%B9%96%E3%83%BB%E4%B8%80%E6%96%B9%E9%80%9A%E8%A1%8C%EF%BC%88%E5%87%BA%E5%8F%A3%EF%BC%89_-_panoramio.jpg"
    },
  },
  {
    id: "slow-down",
    file: "/photos/slow-down.jpg",
    commonsTitle: "File:徐行←.jpg",
    focus: "行",
    text: "徐行",
    textReading: "じょこう",
    where: "Señal de «al paso» en Ōtsu, Shiga",
    caption: "徐行 se lee じょこう: «circula despacio». 行 suena こう (on), no いく. En tráfico casi todo va en on.",
    credit: {
      author: "運動会プロテインパワー",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%BE%90%E8%A1%8C%E2%86%90.jpg"
    },
  },
  {
    id: "crosswalk",
    file: "/photos/crosswalk.jpg",
    commonsTitle: "File:Child Pedestrian Crossing Sign in Japan.jpg",
    focus: "歩",
    text: "横断歩道",
    textReading: "おうだんほどう",
    where: "Paso de peatones en Japón",
    caption: "横断歩道 se lee おうだんほどう. 歩 suena ほ (on). Es «camino para cruzar andando».",
    credit: {
      author: "運動会プロテインパワー",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AChild_Pedestrian_Crossing_Sign_in_Japan.jpg"
    },
  },
  {
    id: "crosswalk-road",
    file: "/photos/crosswalk.jpg",
    commonsTitle: "File:Child Pedestrian Crossing Sign in Japan.jpg",
    focus: "道",
    text: "横断歩道",
    textReading: "おうだんほどう",
    where: "Paso de peatones en Japón",
    caption: "道 suena どう (on) en 歩道. No es みち: aquí es la mitad de una palabra de tráfico.",
    credit: {
      author: "運動会プロテインパワー",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AChild_Pedestrian_Crossing_Sign_in_Japan.jpg"
    },
  },
  {
    id: "stop-once",
    file: "/photos/stop-once.jpg",
    commonsTitle: "File:危い 一時停止 (2450882964).jpg",
    focus: "時",
    text: "一時停止",
    textReading: "いちじていし",
    where: "Señal antigua en Hagi",
    caption: "一時停止 se lee いちじていし: «stop». 時 suena じ (on). Es la fórmula legal, más formal que 止まれ.",
    credit: {
      author: "George Dorn",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%8D%B1%E3%81%84_%E4%B8%80%E6%99%82%E5%81%9C%E6%AD%A2_%282450882964%29.jpg"
    },
  },
  {
    id: "construction",
    file: "/photos/construction.jpg",
    commonsTitle: "File:工事中の看板 - panoramio.jpg",
    focus: "事",
    text: "工事中",
    textReading: "こうじちゅう",
    where: "Obras en la calle",
    caption: "工事中 se lee こうじちゅう. 事 suena じ (on) y 中 ちゅう: «en medio de las obras».",
    credit: {
      author: "運転太郎",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%B7%A5%E4%BA%8B%E4%B8%AD%E3%81%AE%E7%9C%8B%E6%9D%BF_-_panoramio.jpg"
    },
  },
  {
    id: "construction-naka",
    file: "/photos/construction.jpg",
    commonsTitle: "File:工事中の看板 - panoramio.jpg",
    focus: "中",
    text: "工事中",
    textReading: "こうじちゅう",
    where: "Obras en la calle",
    caption: "中 al final de un cartel (営業中, 工事中, 準備中) se lee ちゅう, on: «en curso».",
    credit: {
      author: "運転太郎",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%B7%A5%E4%BA%8B%E4%B8%AD%E3%81%AE%E7%9C%8B%E6%9D%BF_-_panoramio.jpg"
    },
  },
  {
    id: "closed-today",
    file: "/photos/closed-today.jpg",
    commonsTitle: "File:本日は臨時休業 2011-03-15 (5698791923).jpg",
    focus: "休",
    text: "臨時休業",
    textReading: "りんじきゅうぎょう",
    where: "7-Eleven cerrado, marzo de 2011",
    caption: "休業 se lee きゅうぎょう. 休 suena きゅう (on): «parar el negocio». El kun やすむ queda para descansar una persona.",
    credit: {
      author: "allegro Takahi",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%9C%AC%E6%97%A5%E3%81%AF%E8%87%A8%E6%99%82%E4%BC%91%E6%A5%AD_2011-03-15_%285698791923%29.jpg"
    },
  },
  {
    id: "closed-honjitsu",
    file: "/photos/closed-honjitsu.jpg",
    commonsTitle: "File:本日休業 出入口 (14512991318).jpg",
    focus: "本",
    text: "本日休業",
    textReading: "ほんじつきゅうぎょう",
    where: "Puerta con el cartel de cerrado",
    caption: "本日 se lee ほんじつ: «hoy». 本 suena ほん (on), no もと. Es la fórmula de las tiendas.",
    credit: {
      author: "oddstranger from Tokyo, Japan",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%9C%AC%E6%97%A5%E4%BC%91%E6%A5%AD_%E5%87%BA%E5%85%A5%E5%8F%A3_%2814512991318%29.jpg"
    },
  },
  {
    id: "prep-naka",
    file: "/photos/preparing.jpg",
    commonsTitle: "File:NGO Kita Tabata 2-13 20221011-04.jpg",
    focus: "準",
    text: "準備中",
    textReading: "じゅんびちゅう",
    where: "Restaurante en Nagoya aún no abierto",
    caption: "準備中 se lee じゅんびちゅう: «estamos preparando». 準 suena じゅん (on). Lo verás en muchas persianas a primera hora.",
    credit: {
      author: "円周率３パーセント",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3ANGO_Kita_Tabata_2-13_20221011-04.jpg"
    },
  },
  {
    id: "elementary",
    file: "/photos/elementary.jpg",
    commonsTitle: "File:雷小学校校門.jpg",
    focus: "学",
    text: "小学校",
    textReading: "しょうがっこう",
    where: "Puerta de una escuela primaria",
    caption: "小学校 se lee しょうがっこう. 学 suena がっ (on con sokuon): «escuela pequeña», la primaria.",
    credit: {
      author: "Mizuki Kusakawa",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%9B%B7%E5%B0%8F%E5%AD%A6%E6%A0%A1%E6%A0%A1%E9%96%80.jpg"
    },
  },
  {
    id: "elementary-small",
    file: "/photos/elementary-ima.jpg",
    commonsTitle: "File:今町小学校校門.jpg",
    focus: "小",
    text: "小学校",
    textReading: "しょうがっこう",
    where: "Antigua escuela primaria Ima-machi",
    caption: "小 suena しょう (on) en 小学校, no ちいさい. Los nombres de centro escolar van en on.",
    credit: {
      author: "Unknown authorUnknown author",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%BB%8A%E7%94%BA%E5%B0%8F%E5%AD%A6%E6%A0%A1%E6%A0%A1%E9%96%80.jpg"
    },
  },
  {
    id: "junior-high",
    file: "/photos/junior-high.jpg",
    commonsTitle: "File:奥多摩町立古里中学校正門.JPG",
    focus: "校",
    text: "中学校",
    textReading: "ちゅうがっこう",
    where: "Instituto de Okutama",
    caption: "中学校 se lee ちゅうがっこう. 校 suena こう (on) y solo se usa en nombres de escuela.",
    credit: {
      author: "Yoshimisss",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%A5%A5%E5%A4%9A%E6%91%A9%E7%94%BA%E7%AB%8B%E5%8F%A4%E9%87%8C%E4%B8%AD%E5%AD%A6%E6%A0%A1%E6%AD%A3%E9%96%80.JPG"
    },
  },
  {
    id: "high-school",
    file: "/photos/high-school.jpg",
    commonsTitle: "File:Ichikawa high school May 2026 01.jpg",
    focus: "高",
    text: "高等学校",
    textReading: "こうとうがっこう",
    where: "Instituto de Ichikawa, Hyōgo",
    caption: "高等学校 se lee こうとうがっこう. 高 suena こう (on): el instituto, no «alto».",
    credit: {
      author: "Chacmool",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AIchikawa_high_school_May_2026_01.jpg"
    },
  },
  {
    id: "hospital-oita",
    file: "/photos/hospital-oita.jpg",
    commonsTitle: "File:大分岡病院 看板.jpg",
    focus: "院",
    text: "病院",
    textReading: "びょういん",
    where: "Hospital Ōita Oka",
    caption: "病院 se lee びょういん. 院 suena いん (on): «institución». Sale en hospitales, templos y oficinas.",
    credit: {
      author: "デジタルメディア戦略局",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%A4%A7%E5%88%86%E5%B2%A1%E7%97%85%E9%99%A2_%E7%9C%8B%E6%9D%BF.jpg"
    },
  },
  {
    id: "hospital-tokyo",
    file: "/photos/hospital-tokyo-kamata.jpg",
    commonsTitle: "File:東京蒲田病院 正面看板 2026-08-13.jpg",
    focus: "病",
    text: "病院",
    textReading: "びょういん",
    where: "Hospital Tokyo Kamata",
    caption: "病 suena びょう (on) en 病院. No se lee やむ: en la calle, enfermedad va en on.",
    credit: {
      author: "鈴音雨",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%9D%B1%E4%BA%AC%E8%92%B2%E7%94%B0%E7%97%85%E9%99%A2_%E6%AD%A3%E9%9D%A2%E7%9C%8B%E6%9D%BF_2026-08-13.jpg"
    },
  },
  {
    id: "library-kyoto",
    file: "/photos/library-kyoto.jpg",
    commonsTitle: "File:京都府立図書館 看板20250608.jpg",
    focus: "書",
    text: "図書館",
    textReading: "としょかん",
    where: "Biblioteca prefectural de Kioto",
    caption: "図書館 se lee としょかん. 書 suena しょ (on). 図+書+館: «edificio de dibujos y escrituras».",
    credit: {
      author: "川内センタロー",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%BA%AC%E9%83%BD%E5%BA%9C%E7%AB%8B%E5%9B%B3%E6%9B%B8%E9%A4%A8_%E7%9C%8B%E6%9D%BF20250608.jpg"
    },
  },
  {
    id: "library-tajimi",
    file: "/photos/library-tajimi.jpg",
    commonsTitle: "File:Tajimi City Library ac (4).jpg",
    focus: "図",
    text: "図書館",
    textReading: "としょかん",
    where: "Biblioteca municipal de Tajimi",
    caption: "図 suena と (on) en 図書館, una lectura corta que casi solo verás en esta palabra.",
    credit: {
      author: "Asturio Cantabrio",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3ATajimi_City_Library_ac_%284%29.jpg"
    },
  },
  {
    id: "library-city",
    file: "/photos/library-tajimi.jpg",
    commonsTitle: "File:Tajimi City Library ac (4).jpg",
    focus: "市",
    text: "市図書館",
    textReading: "しとしょかん",
    where: "Biblioteca municipal de Tajimi",
    caption: "市 suena し (on) cuando es «ayuntamiento / municipal», no いち de mercado.",
    credit: {
      author: "Asturio Cantabrio",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3ATajimi_City_Library_ac_%284%29.jpg"
    },
  },
  {
    id: "post-kyoto",
    file: "/photos/post-kyoto-utano.jpg",
    commonsTitle: "File:京都宇多野郵便局.JPG",
    focus: "局",
    text: "郵便局",
    textReading: "ゆうびんきょく",
    where: "Oficina de correos de Utano, Kioto",
    caption: "郵便局 se lee ゆうびんきょく. 局 suena きょく (on): «oficina». El kanji de las sucursales.",
    credit: {
      author: "Bergmann",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%BA%AC%E9%83%BD%E5%AE%87%E5%A4%9A%E9%87%8E%E9%83%B5%E4%BE%BF%E5%B1%80.JPG"
    },
  },
  {
    id: "post-seya",
    file: "/photos/post-seya.jpg",
    commonsTitle: "File:瀬谷郵便局 看板 20260712.jpg",
    focus: "便",
    text: "郵便局",
    textReading: "ゆうびんきょく",
    where: "Oficina de correos de Seya",
    caption: "便 suena びん (on sonorizado) en 郵便. No es たより: aquí es «correo».",
    credit: {
      author: "Japanbird",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E7%80%AC%E8%B0%B7%E9%83%B5%E4%BE%BF%E5%B1%80_%E7%9C%8B%E6%9D%BF_20260712.jpg"
    },
  },
  {
    id: "onsen-dogo",
    file: "/photos/onsen-dogo.jpg",
    commonsTitle: "File:道後温泉（本館）看板.JPG",
    focus: "温",
    text: "温泉",
    textReading: "おんせん",
    where: "Dōgo Onsen, Ehime",
    caption: "温泉 se lee おんせん. 温 suena おん (on): agua caliente de manantial, el cartel más típico de balneario.",
    credit: {
      author: "Ayasesaya",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%81%93%E5%BE%8C%E6%B8%A9%E6%B3%89%EF%BC%88%E6%9C%AC%E9%A4%A8%EF%BC%89%E7%9C%8B%E6%9D%BF.JPG"
    },
  },
  {
    id: "onsen-futagawa",
    file: "/photos/onsen-futagawa.jpg",
    commonsTitle: "File:二川温泉案内看板PA070891.jpg",
    focus: "泉",
    text: "温泉",
    textReading: "おんせん",
    where: "Onsen de Futagawa",
    caption: "泉 suena せん (on) en 温泉, no いずみ. En la calle, manantial termal = on.",
    credit: {
      author: "秋空から蛇が降ってきた",
      license: "Public domain",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%BA%8C%E5%B7%9D%E6%B8%A9%E6%B3%89%E6%A1%88%E5%86%85%E7%9C%8B%E6%9D%BFPA070891.jpg"
    },
  },
  {
    id: "shrine-fuji",
    file: "/photos/shrine-fuji.jpg",
    commonsTitle: "File:藤基神社社号標.jpg",
    focus: "社",
    text: "神社",
    textReading: "じんじゃ",
    where: "Piedra con el nombre de un santuario",
    caption: "神社 se lee じんじゃ. 社 suena じゃ (on sonorizado). En un pueblo, 社 a solas a menudo es el santuario, no una empresa.",
    credit: {
      author: "GonN",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E8%97%A4%E5%9F%BA%E7%A5%9E%E7%A4%BE%E7%A4%BE%E5%8F%B7%E6%A8%99.jpg"
    },
  },
  {
    id: "shrine-tamagawa",
    file: "/photos/shrine-tamagawa.jpg",
    commonsTitle: "File:瀬田玉川神社社号標.JPG",
    focus: "川",
    text: "玉川神社",
    textReading: "たまがわじんじゃ",
    where: "Santuario Setatamagawa",
    caption: "玉川 se lee たまがわ. 川 suena がわ (kun sonorizado), igual que en los nombres de río.",
    credit: {
      author: "小池 隆",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E7%80%AC%E7%94%B0%E7%8E%89%E5%B7%9D%E7%A5%9E%E7%A4%BE%E7%A4%BE%E5%8F%B7%E6%A8%99.JPG"
    },
  },
  {
    id: "bridge-terada",
    file: "/photos/bridge-terada.jpg",
    commonsTitle: "File:寺田橋の名板.jpg",
    focus: "橋",
    text: "寺田橋",
    textReading: "てらだばし",
    where: "Placa del puente Terada",
    caption: "寺田橋 se lee てらだばし. 橋 otra vez ばし (kun sonorizado) al final de un nombre.",
    credit: {
      author: "経済特区",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%AF%BA%E7%94%B0%E6%A9%8B%E3%81%AE%E5%90%8D%E6%9D%BF.jpg"
    },
  },
  {
    id: "bridge-chuo",
    file: "/photos/bridge-chuo.jpg",
    commonsTitle: "File:中央大橋の橋名板.jpg",
    focus: "大",
    text: "中央大橋",
    textReading: "ちゅうおうおおはし",
    where: "Puente Chūō Ōhashi",
    caption: "大橋 se lee おおはし. 大 suena おお (kun) cuando el puente se llama «el grande».",
    credit: {
      author: "ぴんぐ2000",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%B8%AD%E5%A4%AE%E5%A4%A7%E6%A9%8B%E3%81%AE%E6%A9%8B%E5%90%8D%E6%9D%BF.jpg"
    },
  },
  {
    id: "bridge-gojo",
    file: "/photos/bridge-gojo.jpg",
    commonsTitle: "File:五条橋の橋名板20201213 02.jpg",
    focus: "五",
    text: "五条橋",
    textReading: "ごじょうばし",
    where: "Puente Gojō",
    caption: "五条橋: 五 suena ご (on). Las calles numeradas de Kioto y sus puentes van en on.",
    credit: {
      author: "経済特区",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E4%BA%94%E6%9D%A1%E6%A9%8B%E3%81%AE%E6%A9%8B%E5%90%8D%E6%9D%BF20201213_02.jpg"
    },
  },
  {
    id: "bridge-yoro",
    file: "/photos/bridge-yoro.jpg",
    commonsTitle: "File:養老橋の橋名板.jpg",
    focus: "橋",
    text: "養老橋",
    textReading: "ようろうばし",
    where: "Puente Yōrō, Tokio",
    caption: "Otra placa de puente. 橋 al final de un nombre propio casi siempre es ばし o はし, kun.",
    credit: {
      author: "Syced",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%A4%8A%E8%80%81%E6%A9%8B%E3%81%AE%E6%A9%8B%E5%90%8D%E6%9D%BF.jpg"
    },
  },
  {
    id: "prefecture-gunma",
    file: "/photos/national-road.jpg",
    commonsTitle: "File:国道50号 群馬県境 標識 20180318 112443.jpg",
    focus: "県",
    text: "群馬県",
    textReading: "ぐんまけん",
    where: "Límite prefectural en la ruta nacional 50",
    caption: "El cartel grande dice 群馬県. 県 suena けん (on): en cada frontera de prefectura aparece este kanji.",
    credit: {
      author: "Puchi-masashi This photo was taken with Canon PowerShot G9 X Mark II",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%9B%BD%E9%81%9350%E5%8F%B7_%E7%BE%A4%E9%A6%AC%E7%9C%8C%E5%A2%83_%E6%A8%99%E8%AD%98_20180318_112443.jpg"
    },
  },
  {
    id: "ota-city",
    file: "/photos/national-road.jpg",
    commonsTitle: "File:国道50号 群馬県境 標識 20180318 112443.jpg",
    focus: "市",
    text: "太田市",
    textReading: "おおたし",
    where: "Límite prefectural en la ruta nacional 50",
    caption: "Debajo dice 太田市. 市 suena し (on), el mismo on de 都市: en Japón casi todas las ciudades se escriben con 市.",
    credit: {
      author: "Puchi-masashi This photo was taken with Canon PowerShot G9 X Mark II",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%9B%BD%E9%81%9350%E5%8F%B7_%E7%BE%A4%E9%A6%AC%E7%9C%8C%E5%A2%83_%E6%A8%99%E8%AD%98_20180318_112443.jpg"
    },
  },
  {
    id: "national-route-229",
    file: "/photos/national-route.jpg",
    commonsTitle: "File:国道229号と国道277号の重複を示す標識（2019年3月撮影）.jpg",
    focus: "国",
    text: "国道",
    textReading: "こくどう",
    where: "Ruta nacional 229 y 277, Hokkaidō",
    caption: "En el escudo azul se lee 国道. 国 suena こく (on), el kanji n.º 3 más usado: «carretera nacional».",
    credit: {
      author: "BATACHAN",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:%E5%9B%BD%E9%81%93229%E5%8F%B7%E3%81%A8%E5%9B%BD%E9%81%93277%E5%8F%B7%E3%81%AE%E9%87%8D%E8%A4%87%E3%82%92%E7%A4%BA%E3%81%99%E6%A8%99%E8%AD%98%EF%BC%882019%E5%B9%B43%E6%9C%88%E6%92%AE%E5%BD%B1%EF%BC%89.jpg"
    },
  },
  {
    id: "national-route-229-michi",
    file: "/photos/national-route.jpg",
    commonsTitle: "File:国道229号と国道277号の重複を示す標識（2019年3月撮影）.jpg",
    focus: "道",
    text: "国道",
    textReading: "こくどう",
    where: "Ruta nacional 229 y 277, Hokkaidō",
    caption: "道 suena どう (on) en 国道. Es el mismo on que en 道路: en las carreteras casi siempre va en on.",
    credit: {
      author: "BATACHAN",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:%E5%9B%BD%E9%81%93229%E5%8F%B7%E3%81%A8%E5%9B%BD%E9%81%93277%E5%8F%B7%E3%81%AE%E9%87%8D%E8%A4%87%E3%82%92%E7%A4%BA%E3%81%99%E6%A8%99%E8%AD%98%EF%BC%882019%E5%B9%B43%E6%9C%88%E6%92%AE%E5%BD%B1%EF%BC%89.jpg"
    },
  },
  {
    id: "park-sign",
    file: "/photos/park-sign.jpg",
    commonsTitle: "File:宮畑公園の案内板.jpg",
    focus: "園",
    text: "公園",
    textReading: "こうえん",
    where: "Parque Miyahata",
    caption: "公園: 園 suena えん (on). Junto con 公 forma la palabra de todos los parques públicos.",
    credit: {
      author: "Harimawood",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%AE%AE%E7%95%91%E5%85%AC%E5%9C%92%E3%81%AE%E6%A1%88%E5%86%85%E6%9D%BF.jpg"
    },
  },
  {
    id: "gate-shibuya",
    file: "/photos/gate-shibuya.jpg",
    commonsTitle: "File:JRE-Shibuya-Station-Tamagawa-Entrance.jpg",
    focus: "改",
    text: "改札",
    textReading: "かいさつ",
    where: "Torniquetes de la estación de Shibuya",
    caption: "改札 se lee かいさつ: el control de billetes. 改 suena かい (on). Lo verás encima de cada torniquete.",
    credit: {
      author: "Rs1421",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AJRE-Shibuya-Station-Tamagawa-Entrance.jpg"
    },
  },
  {
    id: "gate-nagoya",
    file: "/photos/gate-kintetsu-nagoya.jpg",
    commonsTitle: "File:Kintetsu-Nagoya-STA Front-Gate.jpg",
    focus: "札",
    text: "改札口",
    textReading: "かいさつぐち",
    where: "Acceso principal de Kintetsu Nagoya",
    caption: "改札口 añade 口 ぐち. 札 suena さつ (on): «etiqueta / billete».",
    credit: {
      author: "MaedaAkihiko",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AKintetsu-Nagoya-STA_Front-Gate.jpg"
    },
  },
  {
    id: "cafeteria",
    file: "/photos/cafeteria.jpg",
    commonsTitle: "File:食堂の看板。 (34427142233).jpg",
    focus: "食",
    text: "食堂",
    textReading: "しょくどう",
    where: "Cantina junto al cabo Daio, Mie",
    caption: "食堂 se lee しょくどう: «comedor / fonda». 食 suena しょく (on), no たべる.",
    credit: {
      author: "nobu3withfoxy from Iga,Mie, Japan",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%A3%9F%E5%A0%82%E3%81%AE%E7%9C%8B%E6%9D%BF%E3%80%82_%2834427142233%29.jpg"
    },
  },
  {
    id: "open-hours",
    file: "/photos/open-hours.jpg",
    commonsTitle: "File:ガーナ大使館開館時間.jpg",
    focus: "時",
    text: "開館時間",
    textReading: "かいかんじかん",
    where: "Horario de la embajada de Ghana en Tokio",
    caption: "開館時間 se lee かいかんじかん. 時 suena じ (on) en 時間, la palabra de siempre para «hora / horario».",
    credit: {
      author: "Senkaku Islands",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E3%82%AC%E3%83%BC%E3%83%8A%E5%A4%A7%E4%BD%BF%E9%A4%A8%E9%96%8B%E9%A4%A8%E6%99%82%E9%96%93.jpg"
    },
  },
  {
    id: "open-hours-kai",
    file: "/photos/open-hours.jpg",
    commonsTitle: "File:ガーナ大使館開館時間.jpg",
    focus: "開",
    text: "開館",
    textReading: "かいかん",
    where: "Horario de la embajada de Ghana en Tokio",
    caption: "開館 se lee かいかん: «abrir el edificio». 開 suena かい (on). El gemelo es 閉館.",
    credit: {
      author: "Senkaku Islands",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E3%82%AC%E3%83%BC%E3%83%8A%E5%A4%A7%E4%BD%BF%E9%A4%A8%E9%96%8B%E9%A4%A8%E6%99%82%E9%96%93.jpg"
    },
  },
  {
    id: "paid-parking",
    file: "/photos/paid-parking.jpg",
    commonsTitle: "File:加藤駅南口月極有料駐車場 - panoramio.jpg",
    focus: "有",
    text: "有料駐車場",
    textReading: "ゆうりょうちゅうしゃじょう",
    where: "Aparcamiento de pago junto a una estación",
    caption: "有料 se lee ゆうりょう: «de pago». 有 suena ゆう (on). Lo contrario es 無料.",
    credit: {
      author: "運転太郎",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%8A%A0%E8%97%A4%E9%A7%85%E5%8D%97%E5%8F%A3%E6%9C%88%E6%A5%B5%E6%9C%89%E6%96%99%E9%A7%90%E8%BB%8A%E5%A0%B4_-_panoramio.jpg"
    },
  },
  {
    id: "free-road",
    file: "/photos/free-road.png",
    commonsTitle: "File:無料区間.png",
    focus: "無",
    text: "無料",
    textReading: "むりょう",
    where: "Entrada al tramo gratuito de una autovía",
    caption: "無料 se lee むりょう: «gratis». 無 suena む (on), el kanji de «no hay».",
    credit: {
      author: "UDJP",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E7%84%A1%E6%96%99%E5%8C%BA%E9%96%93.png"
    },
  },
  {
    id: "danger-jump",
    file: "/photos/danger-train.jpg",
    commonsTitle: "File:神戸市営地下鉄総合運動公園駅駆け込み乗車危険看板.jpg",
    focus: "危",
    text: "危険",
    textReading: "きけん",
    where: "Andén del metro de Kobe",
    caption: "危険 se lee きけん. 危 suena き (on). Este cartel avisa de no subir al tren a la carrera.",
    credit: {
      author: "NatsuTV",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E7%A5%9E%E6%88%B8%E5%B8%82%E5%96%B6%E5%9C%B0%E4%B8%8B%E9%89%84%E7%B7%8F%E5%90%88%E9%81%8B%E5%8B%95%E5%85%AC%E5%9C%92%E9%A7%85%E9%A7%86%E3%81%91%E8%BE%BC%E3%81%BF%E4%B9%97%E8%BB%8A%E5%8D%B1%E9%99%BA%E7%9C%8B%E6%9D%BF.jpg"
    },
  },
  {
    id: "no-bike-kobe",
    file: "/photos/no-bike-kobe.jpg",
    commonsTitle: "File:新長田駅 駐輪禁止 (14570939279).jpg",
    focus: "禁",
    text: "駐輪禁止",
    textReading: "ちゅうりんきんし",
    where: "Estación de Shin-Nagata, Kobe",
    caption: "駐輪禁止 se lee ちゅうりんきんし: «prohibido aparcar bicis». 禁 suena きん (on) y solo se usa en prohibiciones.",
    credit: {
      author: "Antonio Tajuelo",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%96%B0%E9%95%B7%E7%94%B0%E9%A7%85_%E9%A7%90%E8%BC%AA%E7%A6%81%E6%AD%A2_%2814570939279%29.jpg"
    },
  },
  {
    id: "no-bike-sensoji",
    file: "/photos/no-bike-sensoji.jpg",
    commonsTitle: "File:駐車駐輪禁止 浅草寺 (12151786405).jpg",
    focus: "寺",
    text: "浅草寺",
    textReading: "せんそうじ",
    where: "Senso-ji, Asakusa",
    caption: "浅草寺 se lee せんそうじ. 寺 suena じ (on) al final del nombre de un templo budista.",
    credit: {
      author: "Ishikawa Ken",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%A7%90%E8%BB%8A%E9%A7%90%E8%BC%AA%E7%A6%81%E6%AD%A2_%E6%B5%85%E8%8D%89%E5%AF%BA_%2812151786405%29.jpg"
    },
  },
  {
    id: "no-parking-car",
    file: "/photos/no-parking-car.jpg",
    commonsTitle: "File:駐車禁止 (14447080673).jpg",
    focus: "駐",
    text: "駐車禁止",
    textReading: "ちゅうしゃきんし",
    where: "Señal de no aparcar (coches)",
    caption: "駐車禁止 se lee ちゅうしゃきんし. 駐 suena ちゅう (on): «dejar el vehículo». El cartel de coche, no de bici.",
    credit: {
      author: "Jacob Ehnmark",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%A7%90%E8%BB%8A%E7%A6%81%E6%AD%A2_%2814447080673%29.jpg"
    },
  },
  {
    id: "school-route",
    file: "/photos/school-route.jpg",
    commonsTitle: "File:通学路。 - panoramio.jpg",
    focus: "通",
    text: "通学路",
    textReading: "つうがくろ",
    where: "Camino escolar",
    caption: "通学路 se lee つうがくろ. 通 suena つう (on): «el camino para ir al cole». Lo pintan en el asfalto.",
    credit: {
      author: "shigen",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E9%80%9A%E5%AD%A6%E8%B7%AF%E3%80%82_-_panoramio.jpg"
    },
  },
  {
    id: "school-route-elem",
    file: "/photos/school-route-ochiai.jpg",
    commonsTitle: "File:落合小学校 通学路 - panoramio.jpg",
    focus: "学",
    text: "小学校",
    textReading: "しょうがっこう",
    where: "Camino escolar hacia Ochiai",
    caption: "Otra 小学校 en un camino escolar. 学 otra vez がっ: vas a ver este compuesto en cada barrio.",
    credit: {
      author: "cora_cola 茶々丸",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E8%90%BD%E5%90%88%E5%B0%8F%E5%AD%A6%E6%A0%A1_%E9%80%9A%E5%AD%A6%E8%B7%AF_-_panoramio.jpg"
    },
  },
  {
    id: "city-hall",
    file: "/photos/city-hall-kyotanabe.jpg",
    commonsTitle: "File:Kyotanabecity office sign.JPG",
    focus: "市",
    text: "市役所",
    textReading: "しやくしょ",
    where: "Ayuntamiento de Kyōtanabe",
    caption: "市役所 se lee しやくしょ. 市 suena し (on): el ayuntamiento, no el mercado.",
    credit: {
      author: "Mti",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AKyotanabecity_office_sign.JPG"
    },
  },
  {
    id: "city-hall-yaku",
    file: "/photos/city-hall-kyotanabe.jpg",
    commonsTitle: "File:Kyotanabecity office sign.JPG",
    focus: "役",
    text: "市役所",
    textReading: "しやくしょ",
    where: "Ayuntamiento de Kyōtanabe",
    caption: "役 suena やく (on) en 役所: «oficios / administración». Palabra de todos los ayuntamientos.",
    credit: {
      author: "Mti",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AKyotanabecity_office_sign.JPG"
    },
  },
  {
    id: "koban",
    file: "/photos/koban-sugamo.jpg",
    commonsTitle: "File:巣鴨警察署 巣鴨駅前交番 2008 (2936107087).jpg",
    focus: "交",
    text: "交番",
    textReading: "こうばん",
    where: "Comisaría de barrio en Sugamo",
    caption: "交番 se lee こうばん. 交 suena こう (on). Es la caseta de policía de cada barrio, con el kanji bien grande.",
    credit: {
      author: "Go Ikeda",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E5%B7%A3%E9%B4%A8%E8%AD%A6%E5%AF%9F%E7%BD%B2_%E5%B7%A3%E9%B4%A8%E9%A7%85%E5%89%8D%E4%BA%A4%E7%95%AA_2008_%282936107087%29.jpg"
    },
  },
  {
    id: "koban-ban",
    file: "/photos/koban-urawa.jpg",
    commonsTitle: "File:Urawa Police Station Urawa Ekimae Koban 1.jpg",
    focus: "番",
    text: "交番",
    textReading: "こうばん",
    where: "Comisaría frente a la estación de Urawa",
    caption: "番 suena ばん (on) en 交番. El mismo kanji de «turno» que en 一番, aquí es la comisaría.",
    credit: {
      author: "Ebiebi2",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AUrawa_Police_Station_Urawa_Ekimae_Koban_1.jpg"
    },
  },
  {
    id: "extinguisher",
    file: "/photos/extinguisher.jpg",
    commonsTitle: "File:消火器.jpg",
    focus: "火",
    text: "消火器",
    textReading: "しょうかき",
    where: "Extintor en un edificio japonés",
    caption: "消火器 se lee しょうかき. 火 suena か (on), no ひ: «aparato para apagar el fuego».",
    credit: {
      author: "eisuke1125",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%B6%88%E7%81%AB%E5%99%A8.jpg"
    },
  },
  {
    id: "extinguisher-kesu",
    file: "/photos/extinguisher-hachioji.jpg",
    commonsTitle: "File:消火器 (928381238).jpg",
    focus: "消",
    text: "消火器",
    textReading: "しょうかき",
    where: "Extintor en Hachiōji",
    caption: "消 suena しょう (on) en 消火. El kun きえる se queda para «apagarse una luz», no para el cartel.",
    credit: {
      author: "Shinichi Sugiyama",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%B6%88%E7%81%AB%E5%99%A8_%28928381238%29.jpg"
    },
  },
  {
    id: "fukuoka-city-hall",
    file: "/photos/fukuoka-city-hall.jpg",
    commonsTitle: "File:Fukuoka City Hall Main Bldg the building name sign Tenjin 1-chōme Chūō-ku Fukuoka 20250224.jpg",
    focus: "福",
    text: "福岡市",
    textReading: "ふくおかし",
    where: "Ayuntamiento de Fukuoka",
    caption: "福岡市 se lee ふくおかし. 福 suena ふく (on). El cartel del edificio del ayuntamiento.",
    credit: {
      author: "Hirho",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AFukuoka_City_Hall_Main_Bldg_the_building_name_sign_Tenjin_1-ch%C5%8Dme_Ch%C5%AB%C5%8D-ku_Fukuoka_20250224.jpg"
    },
  },
  {
    id: "ekoda-north",
    file: "/photos/ekoda-north.jpg",
    commonsTitle: "File:Ekoda Station 2011-07-16-02.jpg",
    focus: "北",
    text: "北口",
    textReading: "きたぐち",
    where: "Pasillo hacia la salida norte de Ekoda",
    caption: "北口 se lee きたぐち. 北 suena きた (kun) y 口 ぐち. En las estaciones, los puntos cardinales van en kun.",
    credit: {
      author: "たかも",
      license: "Public domain",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3AEkoda_Station_2011-07-16-02.jpg"
    },
  },
  {
    id: "yokokawa-gate",
    file: "/photos/yokokawa-gate.jpg",
    commonsTitle: "File:横川駅耐震工事改札口変更看板.jpg",
    focus: "横",
    text: "横川",
    textReading: "よこかわ",
    where: "Aviso de obras en la estación de Yokokawa",
    caption: "横川 se lee よこかわ. 横 suena よこ (kun): «de lado», el mismo kun que en 横浜.",
    credit: {
      author: "X68",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E6%A8%AA%E5%B7%9D%E9%A7%85%E8%80%90%E9%9C%87%E5%B7%A5%E4%BA%8B%E6%94%B9%E6%9C%AD%E5%8F%A3%E5%A4%89%E6%9B%B4%E7%9C%8B%E6%9D%BF.jpg"
    },
  },
  {
    id: "level-crossing",
    file: "/photos/level-crossing.jpg",
    commonsTitle: "File:踏切警報機.jpg",
    focus: "踏",
    text: "踏切",
    textReading: "ふみきり",
    where: "Paso a nivel cerca de Higashigasaki",
    caption: "踏切 se lee ふみきり. 踏 suena ふみ (kun): «pisar y cortar la vía», el paso a nivel.",
    credit: {
      author: "Nekosuki600",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3A%E8%B8%8F%E5%88%87%E8%AD%A6%E5%A0%B1%E6%A9%9F.jpg"
    },
  },
  {
    id: "no-vacant-taxi",
    file: "/photos/no-vacant-taxi.jpg",
    commonsTitle: "File:Road sign prohibit vacant taxi.JPG",
    focus: "空",
    text: "空車",
    textReading: "くうしゃ",
    where: "Señal que prohíbe el paso a taxis libres",
    caption: "Otra vez 空車 くうしゃ, ahora en una señal de tráfico. 空 en on: el taxi con el letrero de «libre».",
    credit: {
      author: "Taichi Hiromatsu《スペルチェック》",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File%3ARoad_sign_prohibit_vacant_taxi.JPG"
    },
  },
]
