/**
 * Frases de ejemplo escritas para este proyecto (no vienen de ningún corpus).
 *
 * Objetivo: ver el kanji dentro de una frase real y entender *qué lectura* usa
 * y por qué. Por eso muchos kanji tienen dos frases: una con lectura kun
 * (kanji solo o con hiragana) y otra con lectura on (kanji pegado a otro).
 *
 * Notación: ver `scripts/lib/jp-tokens.mjs`.
 *   - `漢字:よみ` pinta furigana sobre ese bloque de kanji
 *   - `*` marca la palabra que se estudia
 *   - `focus` da la palabra completa cuando el kanji lleva okurigana
 *
 * `tier` sigue la escalera de dificultad (`src/lib/difficulty.ts`):
 *   1 = frase mínima con un solo kanji, 4 = frase con compuestos.
 */

/** Mundo 1 (primero de primaria): frases muy cortas, casi todo en hiragana. */
const WORLD_1 = [
  // Etapa 1
  { k: '日', jp: '*日:ひ が のぼる。', es: 'Sale el sol.', tier: 1 },
  { k: '日', jp: '*日曜日:にちようび は やすみです。', es: 'El domingo es día de descanso.', tier: 3 },
  { k: '一', jp: '*一:ひと つ ください。', focus: '一つ|ひとつ', es: 'Uno, por favor.', tier: 1 },
  { k: '一', jp: '*一年生:いちねんせい に なる。', es: 'Paso a primero.', tier: 3 },
  { k: '人', jp: '*人:ひと が おおい。', es: 'Hay mucha gente.', tier: 1 },
  { k: '人', jp: '*三人:さんにん で あるく。', es: 'Caminamos los tres.', tier: 3 },
  { k: '年', jp: '*一年:いちねん は ながい。', es: 'Un año es largo.', tier: 2 },
  { k: '年', jp: '*今年:ことし は ゆきが おおい。', es: 'Este año hay mucha nieve.', tier: 3 },
  { k: '大', jp: '*大:おお きい いぬ。', focus: '大きい|おおきい', es: 'Un perro grande.', tier: 1 },
  { k: '大', jp: '*大学:だいがく に いく。', es: 'Voy a la universidad.', tier: 3 },
  { k: '十', jp: '*十:とお まで かぞえる。', es: 'Contar hasta diez.', tier: 1 },
  { k: '十', jp: '*十月:じゅうがつ に あう。', es: 'Nos vemos en octubre.', tier: 3 },

  // Etapa 2
  { k: '二', jp: '*二:ふた つ あります。', focus: '二つ|ふたつ', es: 'Hay dos.', tier: 1 },
  { k: '二', jp: '*二月:にがつ は さむい。', es: 'Febrero es frío.', tier: 3 },
  { k: '本', jp: '*本:ほん を よむ。', es: 'Leo un libro.', tier: 1 },
  { k: '中', jp: '*中:なか に はいる。', es: 'Entrar dentro.', tier: 1 },
  { k: '中', jp: '*中学:ちゅうがく の せんせい。', es: 'Un profesor de secundaria.', tier: 3 },
  { k: '出', jp: '*出:で る じかん。', focus: '出る|でる', es: 'La hora de salir.', tier: 2 },
  { k: '出', jp: '*出口:でぐち は あちらです。', es: 'La salida está por allí.', tier: 2 },
  { k: '三', jp: '*三:みっ つ かいます。', focus: '三つ|みっつ', es: 'Compro tres.', tier: 1 },
  { k: '三', jp: '*三月:さんがつ に あう。', es: 'Nos vemos en marzo.', tier: 3 },
  { k: '見', jp: '*見:み る のが すき。', focus: '見る|みる', es: 'Me gusta mirar.', tier: 1 },

  // Etapa 3
  { k: '月', jp: '*月:つき が きれいだ。', es: 'La luna está bonita.', tier: 1 },
  { k: '月', jp: '*一月:いちがつ は さむい。', es: 'Enero es frío.', tier: 3 },
  { k: '生', jp: '*生:い きる ちから。', focus: '生きる|いきる', es: 'La fuerza de vivir.', tier: 2 },
  { k: '生', jp: '*学生:がくせい です。', es: 'Soy estudiante.', tier: 3 },
  { k: '五', jp: '*五:いつ つ の いし。', focus: '五つ|いつつ', es: 'Cinco piedras.', tier: 1 },
  { k: '五', jp: '*五月:ごがつ に さく。', es: 'Florece en mayo.', tier: 3 },
  { k: '上', jp: '*上:うえ を みる。', es: 'Mirar hacia arriba.', tier: 1 },
  { k: '四', jp: '*四:よっ つ たべる。', focus: '四つ|よっつ', es: 'Me como cuatro.', tier: 1 },
  { k: '四', jp: '*四月:しがつ に はじまる。', es: 'Empieza en abril.', tier: 3 },
  { k: '金', jp: 'お *金:かね を はらう。', es: 'Pagar el dinero.', tier: 2 },
  { k: '金', jp: '*金曜日:きんようび に あう。', es: 'Nos vemos el viernes.', tier: 3 },

  // Etapa 4
  { k: '九', jp: '*九:ここの つ の たま。', focus: '九つ|ここのつ', es: 'Nueve bolas.', tier: 1 },
  { k: '九', jp: '*九月:くがつ は あきです。', es: 'Septiembre es otoño.', tier: 3 },
  { k: '入', jp: 'いえ に *入:はい る。', focus: '入る|はいる', es: 'Entrar en la casa.', tier: 2 },
  { k: '入', jp: '*入口:いりぐち で まつ。', es: 'Espero en la entrada.', tier: 2 },
  { k: '立', jp: '*立:た つ こども。', focus: '立つ|たつ', es: 'Un niño de pie.', tier: 1 },
  { k: '手', jp: '*手:て を あげる。', es: 'Levantar la mano.', tier: 1 },
  { k: '手', jp: '*上手:じょうず に かく。', es: 'Escribir bien.', tier: 3 },
  { k: '力', jp: '*力:ちから が つよい。', es: 'Tiene mucha fuerza.', tier: 1 },
  { k: '学', jp: '*学:まな ぶ たのしさ。', focus: '学ぶ|まなぶ', es: 'La alegría de aprender.', tier: 2 },
  { k: '学', jp: '*学校:がっこう へ いく。', es: 'Voy a la escuela.', tier: 2 },

  // Etapa 5
  { k: '円', jp: '*百円:ひゃくえん です。', es: 'Son cien yenes.', tier: 2 },
  { k: '子', jp: '*子:こ ども が わらう。', focus: '子ども|こども', es: 'El niño se ríe.', tier: 1 },
  { k: '目', jp: '*目:め を とじる。', es: 'Cerrar los ojos.', tier: 1 },
  { k: '田', jp: '*田:た んぼ が ひろい。', focus: '田んぼ|たんぼ', es: 'El arrozal es amplio.', tier: 2 },
  { k: '八', jp: '*八:やっ つ ならぶ。', focus: '八つ|やっつ', es: 'Se ponen ocho en fila.', tier: 1 },
  { k: '八', jp: '*八月:はちがつ は あつい。', es: 'Agosto es caluroso.', tier: 3 },
  { k: '六', jp: '*六:むっ つ の たまご。', focus: '六つ|むっつ', es: 'Seis huevos.', tier: 1 },
  { k: '六', jp: '*六月:ろくがつ は あめです。', es: 'En junio llueve.', tier: 3 },

  // Etapa 6
  { k: '下', jp: '*下:した を みる。', es: 'Mirar hacia abajo.', tier: 1 },
  { k: '下', jp: '*下手:へた でも たのしい。', es: 'Aunque se me dé mal, me divierto.', tier: 3 },
  { k: '気', jp: '*天気:てんき が いい。', es: 'Hace buen tiempo.', tier: 2 },
  { k: '小', jp: '*小:ちい さい とり。', focus: '小さい|ちいさい', es: 'Un pájaro pequeño.', tier: 1 },
  { k: '小', jp: '*小学校:しょうがっこう に かよう。', es: 'Voy a la escuela primaria.', tier: 3 },
  { k: '七', jp: '*七:なな つ の ほし。', focus: '七つ|ななつ', es: 'Siete estrellas.', tier: 1 },
  { k: '七', jp: '*七月:しちがつ の うみ。', es: 'El mar en julio.', tier: 3 },
  { k: '山', jp: '*山:やま に のぼる。', es: 'Subir a la montaña.', tier: 1 },
  { k: '山', jp: '*火山:かざん が みえる。', es: 'Se ve un volcán.', tier: 3 },
  { k: '正', jp: '*正:ただ しい こたえ。', focus: '正しい|ただしい', es: 'La respuesta correcta.', tier: 2 },
  { k: '正', jp: '*正月:しょうがつ に あそぶ。', es: 'Jugar en Año Nuevo.', tier: 3 },

  // Etapa 7
  { k: '女', jp: '*女:おんな の ひと。', es: 'Una mujer.', tier: 1 },
  { k: '女', jp: '*女子:じょし の がっこう。', es: 'Una escuela de chicas.', tier: 3 },
  { k: '百', jp: '*百:ひゃく まで かぞえる。', es: 'Contar hasta cien.', tier: 2 },
  { k: '先', jp: '*先生:せんせい が はなす。', es: 'El profesor habla.', tier: 1 },
  { k: '先', jp: '*先:さき に いく。', es: 'Voy delante.', tier: 2 },
  { k: '名', jp: '*名前:なまえ を かく。', es: 'Escribo mi nombre.', tier: 2 },
  { k: '川', jp: '*川:かわ で およぐ。', es: 'Nadar en el río.', tier: 1 },
  { k: '川', jp: '*小川:おがわ を わたる。', es: 'Cruzar el arroyo.', tier: 3 },
  { k: '文', jp: '*文:ぶん を よむ。', es: 'Leer una frase.', tier: 2 },

  // Etapa 8
  { k: '千', jp: '*千円:せんえん の ほん。', es: 'Un libro de mil yenes.', tier: 2 },
  { k: '水', jp: '*水:みず を のむ。', es: 'Beber agua.', tier: 1 },
  { k: '水', jp: '*水曜日:すいようび に やすむ。', es: 'Descanso el miércoles.', tier: 3 },
  { k: '男', jp: '*男:おとこ の こ。', es: 'Un niño.', tier: 1 },
  { k: '男', jp: '*男子:だんし が ならぶ。', es: 'Los chicos se ponen en fila.', tier: 3 },
  { k: '村', jp: '*村:むら に かえる。', es: 'Volver al pueblo.', tier: 1 },
  { k: '口', jp: '*口:くち を あける。', es: 'Abrir la boca.', tier: 1 },
  { k: '町', jp: '*町:まち を あるく。', es: 'Caminar por el pueblo.', tier: 1 },

  // Etapa 9
  { k: '校', jp: '*学校:がっこう は たのしい。', es: 'La escuela es divertida.', tier: 2 },
  { k: '空', jp: '*空:そら が あおい。', es: 'El cielo es azul.', tier: 1 },
  { k: '空', jp: '*空気:くうき が つめたい。', es: 'El aire está frío.', tier: 3 },
  { k: '土', jp: '*土:つち を ほる。', es: 'Cavar la tierra.', tier: 1 },
  { k: '土', jp: '*土曜日:どようび に あそぶ。', es: 'Juego el sábado.', tier: 3 },
  { k: '木', jp: '*木:き が たかい。', es: 'El árbol es alto.', tier: 1 },
  { k: '木', jp: '*木曜日:もくようび に あう。', es: 'Nos vemos el jueves.', tier: 3 },
  { k: '車', jp: '*車:くるま が とまる。', es: 'El coche se detiene.', tier: 1 },
  { k: '車', jp: '*電車:でんしゃ に のる。', es: 'Subo al tren.', tier: 2 },
  { k: '石', jp: '*石:いし を なげる。', es: 'Lanzar una piedra.', tier: 1 },

  // Etapa 10
  { k: '足', jp: '*足:あし が いたい。', es: 'Me duele el pie.', tier: 1 },
  { k: '早', jp: '*早:はや く おきる。', focus: '早く|はやく', es: 'Levantarse temprano.', tier: 2 },
  { k: '白', jp: '*白:しろ い ゆき。', focus: '白い|しろい', es: 'Nieve blanca.', tier: 1 },
  { k: '字', jp: '*字:じ が おおきい。', es: 'La letra es grande.', tier: 2 },
  { k: '音', jp: '*音:おと が する。', es: 'Se oye un ruido.', tier: 1 },
  { k: '音', jp: '*音楽:おんがく を きく。', es: 'Escucho música.', tier: 3 },
  { k: '天', jp: '*天気:てんき が わるい。', es: 'Hace mal tiempo.', tier: 2 },

  // Etapa 11
  { k: '火', jp: '*火:ひ を けす。', es: 'Apagar el fuego.', tier: 1 },
  { k: '火', jp: '*火曜日:かようび に はたらく。', es: 'Trabajo el martes.', tier: 3 },
  { k: '花', jp: '*花:はな が さく。', es: 'La flor se abre.', tier: 1 },
  { k: '花', jp: '*花火:はなび を みる。', es: 'Ver fuegos artificiales.', tier: 2 },
  { k: '赤', jp: '*赤:あか い はな。', focus: '赤い|あかい', es: 'Una flor roja.', tier: 1 },
  { k: '青', jp: '*青:あお い そら。', focus: '青い|あおい', es: 'Un cielo azul.', tier: 1 },
  { k: '竹', jp: '*竹:たけ が のびる。', es: 'El bambú crece.', tier: 1 },
  { k: '右', jp: '*右:みぎ に まがる。', es: 'Girar a la derecha.', tier: 1 },

  // Etapa 12
  { k: '森', jp: '*森:もり で あそぶ。', es: 'Jugar en el bosque.', tier: 1 },
  { k: '左', jp: '*左手:ひだりて で かく。', es: 'Escribo con la mano izquierda.', tier: 2 },
  { k: '休', jp: '*休:やす む ひ。', focus: '休む|やすむ', es: 'Un día de descanso.', tier: 2 },
  { k: '休', jp: '*休日:きゅうじつ に でかける。', es: 'Salgo en el día festivo.', tier: 3 },
  { k: '林', jp: '*林:はやし の みち。', es: 'El camino del bosque.', tier: 1 },
  { k: '王', jp: '*王:おう が わらう。', es: 'El rey se ríe.', tier: 2 },
  { k: '玉', jp: '*玉:たま を ころがす。', es: 'Hacer rodar la bola.', tier: 1 },

  // Etapa 13
  { k: '夕', jp: '*夕日:ゆうひ が あかい。', es: 'El sol del atardecer es rojo.', tier: 2 },
  { k: '雨', jp: '*雨:あめ が ふる。', es: 'Llueve.', tier: 1 },
  { k: '草', jp: '*草:くさ が のびる。', es: 'La hierba crece.', tier: 1 },
  { k: '犬', jp: '*犬:いぬ が はしる。', es: 'El perro corre.', tier: 1 },
  { k: '耳', jp: '*耳:みみ が いい。', es: 'Tiene buen oído.', tier: 1 },
  { k: '虫', jp: '*虫:むし を みつける。', es: 'Encontrar un insecto.', tier: 1 },

  // Etapa 14
  { k: '糸', jp: '*糸:いと を きる。', es: 'Cortar el hilo.', tier: 1 },
  { k: '貝', jp: '*貝:かい を ひろう。', es: 'Recoger una concha.', tier: 1 },
]

/** Mundo 2 (segundo de primaria): ya entran compuestos y frases más largas. */
const WORLD_2 = [
  { k: '国', jp: '*国:くに に かえる。', es: 'Volver al país.', tier: 3 },
  { k: '会', jp: '*会:あ う やくそく。', focus: '会う|あう', es: 'La promesa de vernos.', tier: 3 },
  { k: '会', jp: '*会社:かいしゃ に つとめる。', es: 'Trabajo en una empresa.', tier: 3 },
  { k: '長', jp: '*長:なが い かわ。', focus: '長い|ながい', es: 'Un río largo.', tier: 3 },
  { k: '同', jp: '*同:おな じ かたち。', focus: '同じ|おなじ', es: 'La misma forma.', tier: 3 },
  { k: '時', jp: '*時:とき が すぎる。', es: 'El tiempo pasa.', tier: 3 },
  { k: '時', jp: '*時間:じかん が ない。', es: 'No hay tiempo.', tier: 3 },
  { k: '自', jp: '*自分:じぶん で きめる。', es: 'Lo decido yo mismo.', tier: 3 },
  { k: '行', jp: '*行:い く みち。', focus: '行く|いく', es: 'El camino por el que voy.', tier: 3 },
  { k: '社', jp: '*社会:しゃかい を まなぶ。', es: 'Estudiar la sociedad.', tier: 3 },
  { k: '分', jp: '*分:わ かる はなし。', focus: '分かる|わかる', es: 'Una explicación que se entiende.', tier: 3 },
  { k: '後', jp: '*後:あと で いく。', es: 'Voy después.', tier: 3 },
  { k: '前', jp: '*前:まえ に すすむ。', es: 'Avanzar hacia delante.', tier: 3 },
  { k: '前', jp: '*名前:なまえ を よぶ。', es: 'Llamar por el nombre.', tier: 3 },
  { k: '間', jp: '*間:あいだ に すわる。', es: 'Sentarse en medio.', tier: 3 },
  { k: '東', jp: '*東:ひがし の そら。', es: 'El cielo del este.', tier: 3 },
  { k: '東', jp: '*東京:とうきょう に すむ。', es: 'Vivo en Tokio.', tier: 3 },
  { k: '合', jp: '*合:あ う くつ。', focus: '合う|あう', es: 'Unos zapatos que me quedan bien.', tier: 3 },
  { k: '内', jp: '*内:うち に はいる。', es: 'Entrar dentro.', tier: 3 },
  { k: '今', jp: '*今:いま から いく。', es: 'Voy ahora.', tier: 3 },
  { k: '今', jp: '*今日:きょう は はれです。', es: 'Hoy hace sol.', tier: 3 },
  { k: '回', jp: '*一回:いっかい だけ。', es: 'Solo una vez.', tier: 3 },
  { k: '新', jp: '*新:あたら しい くつ。', focus: '新しい|あたらしい', es: 'Unos zapatos nuevos.', tier: 3 },
  { k: '米', jp: '*米:こめ を たく。', es: 'Cocer el arroz.', tier: 3 },
  { k: '高', jp: '*高:たか い やま。', focus: '高い|たかい', es: 'Una montaña alta.', tier: 3 },
  { k: '明', jp: '*明:あか るい へや。', focus: '明るい|あかるい', es: 'Una habitación luminosa.', tier: 3 },
  { k: '京', jp: '*京都:きょうと に いく。', es: 'Voy a Kioto.', tier: 3 },
  { k: '通', jp: '*通:とお る みち。', focus: '通る|とおる', es: 'El camino por donde se pasa.', tier: 3 },
  { k: '外', jp: '*外:そと で あそぶ。', es: 'Jugar fuera.', tier: 3 },
  { k: '言', jp: '*言:い う ことば。', focus: '言う|いう', es: 'Las palabras que se dicen.', tier: 3 },
  { k: '体', jp: '*体:からだ を うごかす。', es: 'Mover el cuerpo.', tier: 3 },
  { k: '首', jp: '*首:くび が いたい。', es: 'Me duele el cuello.', tier: 3 },
  { k: '来', jp: '*来:く る ひと。', focus: '来る|くる', es: 'La persona que viene.', tier: 3 },
  { k: '作', jp: '*作:つく る りょうり。', focus: '作る|つくる', es: 'La comida que preparo.', tier: 3 },
  { k: '強', jp: '*強:つよ い かぜ。', focus: '強い|つよい', es: 'Un viento fuerte.', tier: 3 },
  { k: '公', jp: '*公園:こうえん で あそぶ。', es: 'Juego en el parque.', tier: 3 },
  { k: '思', jp: '*思:おも う こと。', focus: '思う|おもう', es: 'Lo que pienso.', tier: 3 },
  { k: '家', jp: '*家:いえ に かえる。', es: 'Vuelvo a casa.', tier: 3 },
  { k: '話', jp: '*話:はな す こえ。', focus: '話す|はなす', es: 'La voz que habla.', tier: 3 },
  { k: '多', jp: '*多:おお い ひと。', focus: '多い|おおい', es: 'Mucha gente.', tier: 3 },
  { k: '数', jp: '*数:かず を かぞえる。', es: 'Contar el número.', tier: 3 },
  { k: '記', jp: '*日記:にっき を かく。', es: 'Escribo un diario.', tier: 3 },
  { k: '北', jp: '*北:きた の かぜ。', es: 'El viento del norte.', tier: 3 },
  { k: '午', jp: '*午前:ごぜん に あう。', es: 'Nos vemos por la mañana.', tier: 3 },
  { k: '心', jp: '*心:こころ が あたたかい。', es: 'Un corazón cálido.', tier: 3 },
  { k: '教', jp: '*教:おし える せんせい。', focus: '教える|おしえる', es: 'El profesor que enseña.', tier: 3 },
  { k: '書', jp: '*書:か く てがみ。', focus: '書く|かく', es: 'La carta que escribo.', tier: 3 },
  { k: '活', jp: '*生活:せいかつ が かわる。', es: 'La vida cambia.', tier: 3 },
  { k: '元', jp: '*元気:げんき です。', es: 'Estoy bien.', tier: 3 },
  { k: '近', jp: '*近:ちか い みせ。', focus: '近い|ちかい', es: 'Una tienda cercana.', tier: 3 },
  { k: '考', jp: '*考:かんが える ちから。', focus: '考える|かんがえる', es: 'La capacidad de pensar.', tier: 3 },
  { k: '海', jp: '*海:うみ で およぐ。', es: 'Nado en el mar.', tier: 3 },
  { k: '売', jp: '*売:う る みせ。', focus: '売る|うる', es: 'La tienda que vende.', tier: 3 },
  { k: '知', jp: '*知:し る よろこび。', focus: '知る|しる', es: 'La alegría de saber.', tier: 3 },
  { k: '道', jp: '*道:みち を わたる。', es: 'Cruzar la calle.', tier: 3 },
  { k: '半', jp: '*半分:はんぶん たべる。', es: 'Me como la mitad.', tier: 3 },
  { k: '朝', jp: '*朝:あさ に おきる。', es: 'Me levanto por la mañana.', tier: 3 },
  { k: '西', jp: '*西:にし の やま。', es: 'La montaña del oeste.', tier: 3 },
  { k: '広', jp: '*広:ひろ い みち。', focus: '広い|ひろい', es: 'Una calle ancha.', tier: 3 },
  { k: '電', jp: '*電気:でんき を つける。', es: 'Encender la luz.', tier: 3 },
  { k: '少', jp: '*少:すこ し まつ。', focus: '少し|すこし', es: 'Esperar un poco.', tier: 3 },
  { k: '語', jp: '*日本語:にほんご を はなす。', es: 'Hablo japonés.', tier: 4 },
  { k: '止', jp: '*止:と まる くるま。', focus: '止まる|とまる', es: 'Un coche que se detiene.', tier: 3 },
  { k: '聞', jp: '*聞:き く おと。', focus: '聞く|きく', es: 'El sonido que escucho.', tier: 3 },
  { k: '切', jp: '*切:き る かみ。', focus: '切る|きる', es: 'El papel que corto.', tier: 3 },
  { k: '食', jp: '*食:た べる のが すき。', focus: '食べる|たべる', es: 'Me gusta comer.', tier: 3 },
  { k: '食', jp: '*食事:しょくじ の じかん。', es: 'La hora de comer.', tier: 3 },
  { k: '何', jp: '*何:なに を たべる。', es: '¿Qué vas a comer?', tier: 3 },
  { k: '南', jp: '*南:みなみ の しま。', es: 'La isla del sur.', tier: 3 },
  { k: '楽', jp: '*楽:たの しい あさ。', focus: '楽しい|たのしい', es: 'Una mañana divertida.', tier: 3 },
  { k: '店', jp: '*店:みせ が しまる。', es: 'La tienda cierra.', tier: 3 },
  { k: '線', jp: '*線:せん を ひく。', es: 'Trazar una línea.', tier: 3 },
  { k: '声', jp: '*声:こえ が きこえる。', es: 'Se oye una voz.', tier: 3 },
  { k: '親', jp: '*親:おや と はなす。', es: 'Hablo con mis padres.', tier: 3 },
  { k: '頭', jp: '*頭:あたま を あらう。', es: 'Lavarse la cabeza.', tier: 3 },
  { k: '毎', jp: '*毎日:まいにち あるく。', es: 'Camino todos los días.', tier: 3 },
  { k: '門', jp: '*門:もん を あける。', es: 'Abrir la puerta grande.', tier: 3 },
  { k: '答', jp: '*答:こた える こども。', focus: '答える|こたえる', es: 'El niño que responde.', tier: 3 },
  { k: '夜', jp: '*夜:よる に ねる。', es: 'Duermo de noche.', tier: 3 },
  { k: '帰', jp: '*帰:かえ る じかん。', focus: '帰る|かえる', es: 'La hora de volver.', tier: 3 },
  { k: '古', jp: '*古:ふる い てら。', focus: '古い|ふるい', es: 'Un templo antiguo.', tier: 3 },
  { k: '歌', jp: '*歌:うた を うたう。', es: 'Cantar una canción.', tier: 3 },
  { k: '買', jp: '*買:か う パン。', focus: '買う|かう', es: 'El pan que compro.', tier: 3 },
  { k: '光', jp: '*光:ひかり が さす。', es: 'Entra la luz.', tier: 3 },
  { k: '週', jp: '*今週:こんしゅう は いそがしい。', es: 'Esta semana estoy ocupado.', tier: 4 },
  { k: '室', jp: '*教室:きょうしつ に はいる。', es: 'Entro en el aula.', tier: 4 },
  { k: '歩', jp: '*歩:ある く みち。', focus: '歩く|あるく', es: 'El camino que recorro a pie.', tier: 3 },
  { k: '風', jp: '*風:かぜ が つよい。', es: 'El viento es fuerte.', tier: 3 },
  { k: '紙', jp: '*紙:かみ に かく。', es: 'Escribo en el papel.', tier: 3 },
  { k: '母', jp: '*母:はは と あるく。', es: 'Camino con mi madre.', tier: 3 },
  { k: '黒', jp: '*黒:くろ い ねこ。', focus: '黒い|くろい', es: 'Un gato negro.', tier: 3 },
  { k: '春', jp: '*春:はる に さく。', es: 'Florece en primavera.', tier: 3 },
  { k: '読', jp: '*読:よ む ほん。', focus: '読む|よむ', es: 'El libro que leo.', tier: 3 },
  { k: '色', jp: '*色:いろ が きれい。', es: 'El color es bonito.', tier: 3 },
  { k: '友', jp: '*友:とも と あそぶ。', es: 'Juego con mi amigo.', tier: 3 },
  { k: '走', jp: '*走:はし る いぬ。', focus: '走る|はしる', es: 'El perro que corre.', tier: 3 },
  { k: '園', jp: '*公園:こうえん を あるく。', es: 'Camino por el parque.', tier: 3 },
  { k: '秋', jp: '*秋:あき の やま。', es: 'La montaña en otoño.', tier: 3 },
  { k: '馬', jp: '*馬:うま が はしる。', es: 'El caballo corre.', tier: 3 },
  { k: '父', jp: '*父:ちち と はなす。', es: 'Hablo con mi padre.', tier: 3 },
  { k: '夏', jp: '*夏:なつ は あつい。', es: 'El verano es caluroso.', tier: 3 },
  { k: '顔', jp: '*顔:かお を あらう。', es: 'Lavarse la cara.', tier: 3 },
  { k: '船', jp: '*船:ふね に のる。', es: 'Subo al barco.', tier: 3 },
  { k: '池', jp: '*池:いけ に さかな が いる。', es: 'En el estanque hay peces.', tier: 3 },
  { k: '星', jp: '*星:ほし を みる。', es: 'Mirar las estrellas.', tier: 3 },
  { k: '寺', jp: '*寺:てら に いく。', es: 'Voy al templo.', tier: 3 },
  { k: '遠', jp: '*遠:とお い まち。', focus: '遠い|とおい', es: 'Un pueblo lejano.', tier: 3 },
  { k: '弱', jp: '*弱:よわ い ひかり。', focus: '弱い|よわい', es: 'Una luz débil.', tier: 3 },
  { k: '肉', jp: '*肉:にく を やく。', es: 'Asar la carne.', tier: 3 },
  { k: '晴', jp: '*晴:は れる そら。', focus: '晴れる|はれる', es: 'Un cielo que se despeja.', tier: 3 },
  { k: '鳥', jp: '*鳥:とり が とぶ。', es: 'El pájaro vuela.', tier: 3 },
  { k: '冬', jp: '*冬:ふゆ は さむい。', es: 'El invierno es frío.', tier: 3 },
  { k: '昼', jp: '*昼:ひる に たべる。', es: 'Como al mediodía.', tier: 3 },
  { k: '茶', jp: 'お *茶:ちゃ を のむ。', es: 'Bebo té.', tier: 3 },
  { k: '雪', jp: '*雪:ゆき が ふる。', es: 'Nieva.', tier: 3 },
  { k: '弟', jp: '*弟:おとうと と あそぶ。', es: 'Juego con mi hermano pequeño.', tier: 3 },
  { k: '牛', jp: '*牛:うし が あるく。', es: 'La vaca camina.', tier: 3 },
  { k: '魚', jp: '*魚:さかな を たべる。', es: 'Como pescado.', tier: 3 },
  { k: '兄', jp: '*兄:あに と はなす。', es: 'Hablo con mi hermano mayor.', tier: 3 },
  { k: '雲', jp: '*雲:くも が おおい。', es: 'Hay muchas nubes.', tier: 3 },
  { k: '妹', jp: '*妹:いもうと が わらう。', es: 'Mi hermana pequeña se ríe.', tier: 3 },
  { k: '姉', jp: '*姉:あね と でかける。', es: 'Salgo con mi hermana mayor.', tier: 3 },
  { k: '刀', jp: '*刀:かたな を みる。', es: 'Mirar una espada.', tier: 3 },
  { k: '弓', jp: '*弓:ゆみ を ひく。', es: 'Tensar el arco.', tier: 3 },
]

export const SENTENCES = [...WORLD_1, ...WORLD_2]
